// $( document ).ready(function(){
//     // without animation
//     /*
//     $("#close-btn").click(function(){
//        $(".small-image").removeClass('active');
//       $("#show_image_popup").hide();
//     })
  
  
//     $(".small-image").click(function(){
//        // add active class
//        $(this).addClass('active');
//       var image_path = $(this).attr('src'); 
//       $("#show_image_popup").hide();
//       // now st this path to our popup image src
//       $("#show_image_popup").show();
//       $("#large-image").attr('src',image_path);
  
//     })
//   */
  
//     // with animation  
  
//       $("#close-btn").click(function(){
//          // remove active class from all images
//         $(".small-image").removeClass('active');
//         $("#show_image_popup").slideUp();
//       })
  
//       $(".small-image").click(function(){
//           // remove active class from all images
//          $(".small-image").removeClass('active');
//         // add active class
//          $(this).addClass('active');
  
//         var image_path = $(this).attr('src'); 
//         $("#show_image_popup").fadeOut();
//         // now st this path to our popup image src
//         $("#show_image_popup").fadeIn();
//         $("#large-image").attr('src',image_path);
  
//       })
  
//   })

  var small_images  = document.getElementsByClassName("small-image");
  var show_image_popup  = document.getElementById("show_image_popup");
  var large_image  = document.getElementById("large-image");
  var close_btn = document.getElementById("close-btn");
  
  window.addEventListener("load",function(){
  var svgObject = document.getElementById('svg_file').contentDocument;
  var svg = svgObject.getElementsByClassName("small-image")
  });
  
function display_popup_from_svg(id_of_painting){
  var filepath='images/individual_art/'+id_of_painting+'.jpg'
  large_image.src=filepath
  var artistString = '<em>'+artData[id_of_painting]["artist"]+'</em>'+' ('+artData[id_of_painting]['nationality']+', '+artData[id_of_painting]['yob']+'-'+artData[id_of_painting]['yod']+')';
  var titleString = '<i><b>'+artData[id_of_painting]['title']+',</i></b>'+' '+artData[id_of_painting]['paintingDate'];
  var mediumString = artData[id_of_painting]['medium'];
  var extraLinkString = 'For more information please visit <a href='+artData[id_of_painting]["extraLink"]+'> this site</a>.';
  
  document.getElementById("title").innerHTML = titleString;
  document.getElementById("artist").innerHTML = artistString;
  document.getElementById('medium').innerHTML = mediumString;
  document.getElementById('comment').innerHTML = artData[id_of_painting]['comment']
  document.getElementById('extraLink').innerHTML = extraLinkString
  showModal();
}
  
  function showModal(){
    show_image_popup.style.display = 'block';
  }
  
  close_btn.addEventListener("click", function(){
    // before colose the modal we need to remove active class
    for(var i=0; i< small_images.length; i++){
      small_images[i].classList.remove('active');
    }
    // end
    closeModal();
  });
  
  function closeModal(){
    show_image_popup.style.display = 'none';
  }


  //writing in all the artData, there must be a cleaner way to do this. JS is so janky

  let artData = {
      "0101_Pity_WilliamBlake":{
      "title": "Pity",
      "artist": "William Blake",
      "nationality": "English",
      "pob": "Soho",
      "yob": '1757',
      "yod": '1827',
      "pod": "London",
      "paintingDate": "c.1795",
      "medium": "Colour print, finished in ink and watercolour, on paper",
      "style": "Romanticism?",
      "genre": "",
      "period": "",
      "comment": "This artwork is a literal illustration of a double simile from <i>Macbeth</i>, found in the lines: <blockquote>And pity, like a naked new-born babe,\nStriding the blast, or heaven's cherubim, hors'd\nUpon the sightless couriers of the air.\n- Macbeth (1.7.21–23)[3]</blockquote>",
      "extraLink": "https://www.metmuseum.org/art/collection/search/347416"
      },
    "0102_TheBattleOfSanRomano_PaoloUccello":{
      "title": "The Battle of San Romano",
      "artist": "Paolo Uccello",
      "nationality": "Italian",
      "pob": "Pratovecchio",
      "yob": '1397',
      "yod": '1475',
      "pod": "Florence",
      "paintingDate": "c.1438-1440",
      "medium": "Egg tempera with walnut oil and linssed oil on poplar",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The Battle of San Romano is a set of three paintings by the Florentine painter Paolo Uccello depicting events that took place at the Battle of San Romano between Florentine and Sienese forces in 1432. They are significant as revealing the development of linear perspective in early Italian Renaissance painting, and are unusual as a major secular commission. The paintings are in egg tempera on wooden panels, each over 3 metres long. According to the National Gallery,[1] the panels were commissioned by a member of the Bartolini Salimbeni family in Florence sometime between 1435 and 1460. The paintings were much admired in the 15th century; Lorenzo de' Medici so coveted them that he purchased one and had the remaining two forcibly removed to the Palazzo Medici. They are now divided between three collections, the National Gallery, London, the Galleria degli Uffizi, Florence, and the Musée du Louvre, Paris.",
      "extraLink": "https://www.beyondtheyalladog.com/2013/08/the-battle-of-san-romano-in-separate-pieces/"
    },
    "0103_TwoWomen_MaryCockburnMercer":{
      "title": "(Two women)",
      "artist": "Mary Cockburn Mercer",
      "nationality": "Australian",
      "pob": "Scotland",
      "yob": '1882',
      "yod": '1963',
      "pod": "Aubagne",
      "paintingDate": "c. 1940",
      "medium": "Watercolour over pencil on buff paper",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Mary Cockburn Mercer, was an Australian painter. She spent the 1920s and 1930s in Europe, and the 1940s in Melbourne, Australia. Her final years were spent in France. She exhibited with the Contemporary Art Society in Australia. This painting is of two close friends hanging out.",
      "extraLink": "https://www.ngv.vic.gov.au/custom/screens/josephbrown/index.php?artistid=14217&chapter=3"
    },
    "0201_MotherAndChild1907_PabloPicasso":{
      "title": "Mother and child",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": 1907,
      "medium": "Oil on canvas",
      "style": "Cubism",
      "genre": "",
      "period": "",
      "comment": "This is classic Picasso. See how the faces don't look like faces but they feel like faces? Classic Picasso. This is one of many paintings by Picasso depicting a mother and child. So I don't know if he had a weird Freud thing going on, or just lived the subject matter. It also made hunting down this particular mother and child quite difficult. So, you're welcome.",
      "extraLink": "https://arthive.com/pablopicasso/works/376118~Mother_and_child"
    },
    "0202_IfNotNo_RonaldBrooksKitaj":{
      "art": "0202_IfNot,No_RonaldBrooksKitaj",
      "title": "If Not, Not",
      "artist": "Robert Brooks Kitaj",
      "nationality": "American",
      "pob": "Chagrin Falls",
      "yob": 1932,
      "yod": 2007,
      "pod": "Los Angeles",
      "paintingDate": "1975-1976",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Believe it or not, this is a self portrait. The artist is the one holding the baby in bed. This piece also makes many references to TS Elliot's poem The Waste Land. I think it's about the holocaust? The artist is Jewish and has a few pieces exploring that subject. Also great name for a painting.",
      "extraLink": "https://www.nationalgalleries.org/art-and-artists/644/if-not-not"
    },
    "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid":{
      "art": "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid",
      "title": "Q",
      "artist": "David McDiarmid",
      "nationality": "Australian",
      "pob": "Hobart",
      "yob": 1952,
      "yod": 1995,
      "pod": "Sydney",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "So this one is a bit hard to pin down. There was a Rainbow Aphorism series and this one is one of them. David MacDiarmid was an artist, designer and political activist, recognised for his prominent and sustained artistic engagement in issues relating to gay male identity and HIV/AIDS. He is also known for his involvement in the gay liberation movement of the early 1970s, when he was the first person arrested at a gay rights protest in Australia, as well as his artistic direction of the Sydney Gay and Lesbian Mardi Gras. From its inception, McDiarmid's art career encompassed, as both subject and inspiration, gay male sexuality, politics and urban subcultures.",
      "extraLink": "https://fabricquarterly.com.au/2020/10/i-want-a-future-that-lives-up-to-my-past-david-mcdiarmid-and-local-queer-stories/"
    }}
    /*{
      "Art": "0204_GreatStillLifeOnPedestal_PabloPicasso",
      "Title": "Still Life on a Pedestal Table",
      "Artist": "Pablo Picasso",
      "Nationality": "Spanish",
      "POB": "Málaga",
      "YOB": 1881,
      "YOD": 1973,
      "POD": "Mougins",
      "Painting Date": 1931,
      "Medium": "Oil on canvas",
      "Style": "Surrealism",
      "Genre": "Still life",
      "Period": "Neoclassicist & Surrealist Period",
      "Comment": "Another Picasso but this one is surreal instead of a bunch of cubes. I sort of see a dog in there if I squint 🤷. What do you see? When you come out of the toilet mention it to us!",
      "ExtraLink": "https://arthive.com/pablopicasso/works/619569~Still_Life_on_a_Pedestal_Table"
    },
    {
      "Art": "0205_Rembrandt,Self-PortraitWithTwoCircles_Rembrandt",
      "Title": "Self Portrait with Two Circles",
      "Artist": "Rembrandt Harmenszoon van Rijn",
      "Nationality": "Dutch",
      "POB": "Leiden",
      "YOB": 1606,
      "YOD": 1669,
      "POD": "Amsterdam",
      "Painting Date": 1665,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Look at this absolute beast of a painter smashing together this self portrait. The self assured grin. He knows he's considered a master in his art. And then just to flex he throws in two perfectly drawn circles. Because why not?",
      "ExtraLink": "https://www.rembrandtpaintings.com/self-portrait-with-two-circle.jsp"
    },
    {
      "Art": "0206_Pank-a-Squith_Women'sSocialAndPoliticalUnion,London",
      "Title": "Pank-a-Squith",
      "Artist": "British Women's Social and Political Union",
      "Nationality": "-",
      "POB": "-",
      "YOB": "-",
      "YOD": "-",
      "POD": "-",
      "Painting Date": "c. 1909",
      "Medium": "Ink on board",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Roll on up and roll the dice because this one is a board game! Pank-a-Squith was a political board game about the suffragette movement created around 1909. It was created for the British Women's Social and Political Union as a way to generate funds and help spread women's suffrage ideologies. You roll the dice to move the women closer to Parliament house.",
      "ExtraLink": "https://boardgamegeek.com/boardgame/14249/pank-squith"
    },
    {
      "Art": "0207_Lamentation(TheMourningOfChrist)_Giotto",
      "Title": "Lamentation (The Mourning of Christ)",
      "Artist": "Giotto di Bondone",
      "Nationality": "Italian",
      "POB": "Florence",
      "YOB": 1267,
      "YOD": 1337,
      "POD": "Florence",
      "Painting Date": "c. 1304-1306",
      "Medium": "Fresco",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Lamentation (The Mourning of Christ) is a fresco painted c.1305 by the Italian artist Giotto as part of his cycle of the Life of Christ on the interior walls of the Scrovegni Chapel in Padua, Italy. In the painting, the body of the crucified Christ has been lowered from the cross and laid on the ground, surrounded by his grieving mother and disciples. His head is held by Mary, his mother, and his feet by Mary Magdelene. John the Apostle throws his arms wide in despair. To the right, Nicodemus and Joseph of Arimathea wait to prepare the body to be laid in a tomb.",
      "ExtraLink": "https://www.thehistoryofart.org/giotto/lamentation/"
    },
    {
      "Art": "'0301 Primavera - Sandro Botticelli.jpg'",
      "Title": "Primavera",
      "Artist": "Sandro Botticelli",
      "Nationality": "Italian",
      "POB": "Florence",
      "YOB": 1445,
      "YOD": 1510,
      "POD": "Florence",
      "Painting Date": "",
      "Medium": "Tempera on large panel",
      "Style": "Renaissance/Mythological Scene",
      "Genre": "",
      "Period": "",
      "Comment": "You better believe this painting is depicting the Realm of Venus. Zephyr chases the nymph Chloris, who turns into the goddess Flora on the right. Venus is underneath a blindfolded cupid in flight with the three Graces and Mercury on the left.",
      "ExtraLink": "https://news.artnet.com/art-world/sandro-botticelli-primavera-4-things-to-know-1937013"
    },
    {
      "Art": "'0302 Little Thuy - Tráº§n VÄƒn Cáº©n.jpg'",
      "Title": "Little Thuy",
      "Artist": "Trần Văn Cẩn",
      "Nationality": "Vietnamese",
      "POB": "Kiến An",
      "YOB": 1910,
      "YOD": 1994,
      "POD": "Hanoi",
      "Painting Date": 1943,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "The character in the picture is Minh Thuy, the niece of the painter. it was painted in 1943, a few years before the August revolution against the French and Japanese colonial rule. Thuy is still alive (as of 2022), living with her children and grandchildren.",
      "ExtraLink": "https://e.vnexpress.net/news/culture/restoring-national-painting-treasure-little-thuy-a-labor-of-love-4490256.html"
    },
    {
      "Art": "'0303 The Scream - Edvard Munch.jpg'",
      "Title": "The Scream",
      "Artist": "Edvard Munch",
      "Nationality": "Norwegian",
      "POB": "Adalsbruk",
      "YOB": 1863,
      "YOD": 1944,
      "POD": "Oslo",
      "Painting Date": 1893,
      "Medium": "Oil, tempera, and pastel on cardboard",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "What a piece. The artist describes the inspiration for this image thusly: \"I was walking along the road with two friends – the sun was setting – suddenly the sky turned blood red – I paused, feeling exhausted, and leaned on the fence – there was blood and tongues of fire above the blue-black fjord and the city – my friends walked on, and I stood there trembling with anxiety – and I sensed an infinite scream passing through nature.\" 😱😱😱",
      "ExtraLink": "https://www.edvardmunch.org/the-scream.jsp"
    },
    {
      "Art": "'0304 The Rhinoceros - Albrecht Du(umlat)rer.jpg'",
      "Title": "The Rhinocerus",
      "Artist": "Albrecht Dürer",
      "Nationality": "German",
      "POB": "Nuremberg",
      "YOB": 1471,
      "YOD": 1528,
      "POD": "Nuremberg",
      "Painting Date": 1515,
      "Medium": "Woodcut",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This is a woodcut of a rhinocerus that the artist never saw. Instead, this woodcut is based on an anonymous written description and brief sketch of an Indian rhinocerus brought to Lisbon in 1515. The rhinocerus in question subsequently died at sea when the King sent it to the pope as a gift. There is a german inscription on the woodcut that reads: \"On the first of May in the year 1513 AD [sic], the powerful King of Portugal, Manuel of Lisbon, brought such a living animal from India, called the rhinoceros. This is an accurate representation. It is the colour of a speckled tortoise,[1][d] and is almost entirely covered with thick scales. It is the size of an elephant but has shorter legs and is almost invulnerable. It has a strong pointed horn on the tip of its nose, which it sharpens on stones. It is the mortal enemy of the elephant. The elephant is afraid of the rhinoceros, for, when they meet, the rhinoceros charges with its head between its front legs and rips open the elephant's stomach, against which the elephant is unable to defend itself. The rhinoceros is so well-armed that the elephant cannot harm it. It is said that the rhinoceros is fast, impetuous and cunning",
      "ExtraLink": "https://www.rct.uk/collection/800198/a-rhinoceros"
    },
    {
      "Art": "'0305 The Precious Book - Gwen John.jpg'",
      "Title": "The Precious Book",
      "Artist": "Gwen John",
      "Nationality": "Welsh",
      "POB": "Haverfordwest",
      "YOB": 1876,
      "YOD": 1939,
      "POD": "Dieppe",
      "Painting Date": "c. 1916-1926",
      "Medium": "Oil on cavas laid on panel",
      "Style": "Post-Impressionisim",
      "Genre": "",
      "Period": "",
      "Comment": "I couldn't find much information on this piece, only that it is now in the public domain. She's holding the book with a handkerchief, I suppose that makes the book precious.",
      "ExtraLink": "https://www.wikiart.org/en/gwen-john/the-precious-book"
    },
    {
      "Art": "'0306 Women and Bird in the Moonlight - Joan MirÃ³.jpg'",
      "Title": "Women and Bird in the Moonlight",
      "Artist": "Joan Miró",
      "Nationality": "Spanish",
      "POB": "Barcelona",
      "YOB": 1893,
      "YOD": 1983,
      "POD": "Palma",
      "Painting Date": 1949,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "How does this speak to you? What does it say? A seemingly bundle of shapes at first - but there is a moon. There are human shapes. The colours are nice.",
      "ExtraLink": "https://www.tate.org.uk/art/artworks/miro-women-and-bird-in-the-moonlight-n06007"
    },
    {
      "Art": "'0307 Dante running from the three beasts - William Blake.jpg'",
      "Title": "Dante running from the Three Beasts",
      "Artist": "William Blake",
      "Nationality": "English",
      "POB": "Soho",
      "YOB": 1757,
      "YOD": 1827,
      "POD": "London",
      "Painting Date": "1824-1827",
      "Medium": "Pen and ink and watercolour over pencil and black chalk",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Three beasts walk into a bar and Dante runs away. This is Blake illustrating the Divine Comedy (the one with the circles of hell). So, technically a very early version of fan art. Dante looks like he is in Warrior 2.",
      "ExtraLink": "https://artsandculture.google.com/asset/dante-running-from-the-three-beasts-william-blake/-wEF4rg1T7H2JA?hl=en"
    },
    {
      "Art": "'0401 The Great Wave - Katsushika Hokusai.jpg'",
      "Title": "The Great Wave off Kanagawa",
      "Artist": "Katasushika Hokusai",
      "Nationality": "Japanese",
      "POB": "Edo",
      "YOB": 1760,
      "YOD": 1849,
      "POD": "Tokyo",
      "Painting Date": 1831,
      "Medium": "Ukiyo-e (Woodblock print)",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "I got a coffee mug with this image on it. It's a beautiful piece and has been parodied and been an influence for many works throughout the ages. This is a part of a series of other artworks depicting Fuji-Yama and sure enough, Fuji-Yama is at the back, capped in snow. As Japanese read right to left one can argue that the proper way to view this image is to invert it. Doing so makes the wave feel more dangerous, as if it will crush the boat.",
      "ExtraLink": "https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa"
    },
    {
      "Art": "'0501 Ophelia - John Everett Millais.jpg'",
      "Title": "Ophelia",
      "Artist": "John Everett Millais",
      "Nationality": "English",
      "POB": "Southampton",
      "YOB": 1829,
      "YOD": 1896,
      "POD": "Kensington",
      "Painting Date": "1851-1852",
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Imagine being Ophelia, fully clothed and just absolutely drenched in water. You better have hoped it was a hot day because my word I would be misrable if it was anything less than 40 degrees. It's a painting depicting <i>Hamlet</i>, Act IV, Scene vii where she oh..... she falls into a stream a drowns.",
      "ExtraLink": "https://www.tate.org.uk/art/artworks/millais-ophelia-n01506"
    },
    {
      "Art": "'0502 Self-Portrait as the Allegory of Painting - Artemisia Gentileschi.jpg'",
      "Title": "Self-Portrait as the Allegory of Painting (La Pittura)",
      "Artist": "Artemisia Gentileschi",
      "Nationality": "Italian",
      "POB": "Rome",
      "YOB": 1593,
      "YOD": 1653,
      "POD": "Naples",
      "Painting Date": "1638-1639",
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This is a classic self-portrait of an artist. Bonus points for the artist painting another painting in the painting. In fact she is depicting herself as the female personification of Painting, But in a tongue in cheek way I think?",
      "ExtraLink": "https://www.rct.uk/collection/405551/self-portrait-as-the-allegory-of-painting-la-pittura"
    },
    {
      "Art": "'0503 Self-Portrait with Thorn Necklace and Hummingbird - Frida Kahlo.jpg'",
      "Title": "Self-Portrait with Thorn Necklace and Hummingbird",
      "Artist": "Frida Kahlo",
      "Nationality": "Mexican",
      "POB": "Coyoacán",
      "YOB": 1907,
      "YOD": 1954,
      "POD": "Coyoacán",
      "Painting Date": 1940,
      "Medium": "Oil on canvas on masonite",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "It's Kahlo! There's some animals here as well all with their own symbolism associated with them. The hummingbird could symbolise freedom but now it is dead, or it could represent a good luck charm for falling in love or it is meant to invoke the Aztec god of war. The monkey is a symbol of evil, but also she was gifted a spider monkey from Rivera whom she had just divorced. The thorns, is it meant to be christ like or just ouchy ouchy? Don't think about these things too hard. Just look at the pretty animals.",
      "ExtraLink": "https://www.fridakahlo.org/self-portrait-with-thorn-necklace-and-hummingbird.jsp"
    },
    {
      "Art": "'0504 Le Grand Canal - Claude Monet.jpg'",
      "Title": "Le Grand Canal",
      "Artist": "Claude Monet",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1840,
      "YOD": 1926,
      "POD": "Giverny",
      "Painting Date": 1908,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "<i>Le Grand Canal</i> (or <i>The Grand Canal</i> in english) is one of six paintings looking down the canal towards the Salute Church. It's sort of like Magic: The Gathering where you have alternative art of the same card.it sold for $35 million in 2015. Here you can see it in the Toilet Gallery completely free of charge.",
      "ExtraLink": "https://en.wikipedia.org/wiki/Le_Grand_Canal"
    },
    {
      "Art": "'0505 The Kiss - Gustav Klimt.jpg'",
      "Title": "The Kiss",
      "Artist": "Gustav Klimt",
      "Nationality": "Austrian",
      "POB": "Baumgarten",
      "YOB": 1862,
      "YOD": 1918,
      "POD": "Vienna",
      "Painting Date": "1907-1908",
      "Medium": "Oil and gold leaf on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This is a classic piece. It was hailed as pornographic at the time of its unveiling. Actual gold leaf used in it as well.",
      "ExtraLink": "https://www.gustav-klimt.com/The-Kiss.jsp"
    },
    {
      "Art": "'0506 Arnolfini Portrait - Van Eyck.jpg'",
      "Title": "Arnolfini Portrait",
      "Artist": "Jan van Eyck",
      "Nationality": "Netherlandish",
      "POB": "Maaseik",
      "YOB": 1390,
      "YOD": 1441,
      "POD": "Bruges",
      "Painting Date": 1434,
      "Medium": "Oil on oak panel of 3 vertical boards",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Hey check it out, it is Italian merchant Giovanni di Nicolao Arnolfini and his wife (no name). What a wonderful time for both capatalism and the patriarchy! The artist is flexing with the concave mirror in the background and they also threw in a cute little dog for good measure.",
      "ExtraLink": "https://en.wikipedia.org/wiki/Arnolfini_Portrait"
    },
    {
      "Art": "'0507 Sexy Robot - Hajime Sorayama.jpg'",
      "Title": "Robot",
      "Artist": "Hajime Sorayama",
      "Nationality": "Japanese",
      "POB": "Ehime",
      "YOB": 1947,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0601 ArtDeco 1930s.JPG'",
      "Title": "Art, Goût, Beauté",
      "Artist": "Art, Goût, Beauté",
      "Nationality": "-",
      "POB": "-",
      "YOB": "-",
      "YOD": "-",
      "POD": "-",
      "Painting Date": "c.1921-1933",
      "Medium": "Stencil",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This drawing is from the French fashion magazine <i>Art, Goût, Beauté</i>. It ran from 1921 to 1933 and its audience were the more upper class, as it gave hints and tips on how to dress, where to go, and how to behave. I'm not sure who drew this piece, or indeed, which issue it appears in, the internet was sorely lacking on this topics.",
      "ExtraLink": "https://fashionsummedup.com/2021/05/02/art-gout-beaute/"
    },
    {
      "Art": "'0602 Bathers - Rupert Bunny.jpg'",
      "Title": "Bathers",
      "Artist": "Rupert Bunny",
      "Nationality": "Australian",
      "POB": "Melbourne",
      "YOB": 1864,
      "YOD": 1947,
      "POD": "Melbourne",
      "Painting Date": 1906,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Ah, this is the Edwardian life baby. Nothing like hitting up the old salon and just chilling with the gals, ciggy in hand and clothes optional. Make public baths great again.",
      "ExtraLink": "https://learning.qagoma.qld.gov.au/artworks/bathers/"
    },
    {
      "Art": "'0603 Sorrow of the King - Henri Matisse.jpg'",
      "Title": "Sorrow of the King",
      "Artist": "Henri Matisse",
      "Nationality": "French",
      "POB": "Le Cateau-Cambrésis",
      "YOB": 1869,
      "YOD": 1954,
      "POD": "France",
      "Painting Date": 1952,
      "Medium": "Gouache on paper on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Ooooh, I'm the king and I'm sad', is what I imagine the art is saying. This is actually Henri Matisse's last self-portrait. He was in poor health and by the 1950s we had given up painting in favour of creating these collages.",
      "ExtraLink": "https://www.henrimatisse.org/sorrow-of-the-king.jsp"
    },
    {
      "Art": "'0604 William and Shirley, flora and fauna.jpg'",
      "Title": "William and Shirley, flora and fauna 1985",
      "Artist": "William Robinson",
      "Nationality": "Australian",
      "POB": "Brisbane",
      "YOB": 1936,
      "YOD": "Present",
      "POD": "",
      "Painting Date": 1985,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Look at this cute little painting. I got nothing. It's cute!",
      "ExtraLink": "https://www.artlink.com.au/articles/2555/light-years-william-robinson-and-the-creation-stor/"
    },
    {
      "Art": "0701 Forest, Cunningham's Gap - Conrad Martens.jpg",
      "Title": "Forest, Cunningham's Gap",
      "Artist": "Conrad Martens",
      "Nationality": "English",
      "POB": "London",
      "YOB": 1801,
      "YOD": 1878,
      "POD": "North Sydney",
      "Painting Date": 1856,
      "Medium": "Watercolour on paper",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "British-born Conrad Martens settled in Sydney in 1835 and established a lucrative career. Fifteen years later, however, New South Wales suffered an economic downturn and Martens visited the Moreton Bay area in the hope of obtaining commissions from his connections on the rich pastoral lands of the Darling Downs.\nMartens landed in Brisbane on 17 November 1851, and by 11 December was traversing the steep incline of Cunningham's Gap. This route, the most direct and picturesque from the coast, was also very hazardous. Here Martens, like travellers today, experienced a dramatic contrast between the dense rainforest surrounding Cunningham's Gap and the bright, open Downs.\nThe dark, oppressive scene he records is indicative of the way early settlers regarded the Australian bush. The novelist Marcus Clarke later described the Australian landscape as primitive and frightening, the untamed opposite of the English pastoral ideal.\nThe man on horseback is probably Martens himself on one of his two journeys through the area. The figure functions as a symbol of endeavour, about to break through the obscuring bush into the light of a new life.",
      "ExtraLink": "https://learning.qagoma.qld.gov.au/artworks/forest-cunninghams-gap/"
    },
    {
      "Art": "'0702 Untitled 1982 - Jean Michel Basquiat.jpg'",
      "Title": "Untitled (1982)",
      "Artist": "Jean-Michel Basquiat",
      "Nationality": "American",
      "POB": "New York",
      "YOB": 1960,
      "YOD": 1988,
      "POD": "New York",
      "Painting Date": 1982,
      "Medium": "Acrylic, spray paint and oilstick on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This is a skeleton king! Fun fact, Basquiet has numerous artworks he has completed in 1982, most of them titled \"Untitled\" and one of them recently selling for $110 million dollars. So good luck finding anything on this other 1982 untitled piece. Honestly, the artist could have used a better naming convention.",
      "ExtraLink": "https://news.artnet.com/market/jean-michel-basquiat-most-expensive-works-2016-496796"
    },
    {
      "Art": "'0703 Queensland Naïve - James Fardoulus.JPG'",
      "Title": "The start of Burke and Wills 1860",
      "Artist": "James Fardoulys",
      "Nationality": "Greek",
      "POB": "Kythera",
      "YOB": 1900,
      "YOD": 1975,
      "POD": "Brisbane (?)",
      "Painting Date": 1972,
      "Medium": "Oil on board",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Burke and Wills were the first Europeans to cross Australia south to north. They set out in 1860 and finished in 1861. They then died on the return journey. but not all is lost, they expedition uncovered all this grazing land that the Europeans used to further their colonialism.",
      "ExtraLink": "https://www.qagoma.qld.gov.au/exhibition/james-fardoulys/"
    },
    {
      "Art": "'0704 Girl with a Pearl Earring - Johannes Vermeer.jpg'",
      "Title": "Girl with a Pearl Earring",
      "Artist": "Johannes Vermeer",
      "Nationality": "Dutch",
      "POB": "Delft",
      "YOB": 1632,
      "YOD": 1675,
      "POD": "Delft",
      "Painting Date": "c.1665",
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "She was a girl. Wearing an earring. Can I make it anymore obvious? This is one of the all time classics. I know one of the ai art generators was advertising itself by expanding out the borders of the painting. My personal favourite take on this piece is a Dutch astrophysicist who said, um actually the earring looks to be more polished tin on the grounds of the specular reflection, pear shape, and large size.",
      "ExtraLink": "https://en.m.wikipedia.org/wiki/Girl_with_a_Pearl_Earring"
    },
    {
      "Art": "'0705 Bird Stealing Baby - Simon Gende.jpg'",
      "Title": "Bird Stealing Baby",
      "Artist": "Simon Gende",
      "Nationality": "Paupa New Guinea",
      "POB": "Paupa New Guinean",
      "YOB": 1969,
      "YOD": "Present",
      "POD": "",
      "Painting Date": 2018,
      "Medium": "Acrylic on cotton duck",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This piece is based off a PNG story where there are no men in a village so the bird goes and gets a baby from another place. And the new clan call him Pigeon. All the artists works continue the story (the link below is a wonderful youtube video where he describes it all).",
      "ExtraLink": "https://youtu.be/o2pjPxaB5cg"
    },
    {
      "Art": "'0706 Water Lillies - Claude Monet.jpg'",
      "Title": "Water Lilies",
      "Artist": "Claude Monet",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1840,
      "YOD": 1926,
      "POD": "Giverny",
      "Painting Date": "1920-1926",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0801 -A_Sunday_on_La_Grande_Jatte - Gorges Seurat 1884.jpg'",
      "Title": "A Sunday on La Grande Jatte",
      "Artist": "Gorges Seurat",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1859,
      "YOD": 1891,
      "POD": "Paris",
      "Painting Date": 1884,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "Although you may not think it, this painting is actually massive at 2x3m. I heavily recommend reading the link for the details on this piece because it is fascinating if just from a technical perspective. This artwork was painted with a technique known as Pointillism, basically the entire thing is made up of small uniform dots and our brains mix together the colours that are close to each other.",
      "ExtraLink": "https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884"
    },
    {
      "Art": "'0802 The Fighting Temeraire - Joseph Mallord William Turner.jpg'",
      "Title": "The Fighting Temeraire",
      "Artist": "Joseph Mallard William Turner",
      "Nationality": "English",
      "POB": "Covent Garden",
      "YOB": 1775,
      "YOD": 1851,
      "POD": "Chelsea",
      "Painting Date": 1838,
      "Medium": "Oil on canvas",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0803 Starry Night - Van Gogh.jpg'",
      "Title": "",
      "Artist": "Vincent van Gogh",
      "Nationality": "Dutch",
      "POB": "Zundert",
      "YOB": 1853,
      "YOD": 1890,
      "POD": "Auvers-sur-Oise",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0804 Nighthawks - Edward Hopper.jpg'",
      "Title": "",
      "Artist": "Edward Hopper",
      "Nationality": "American",
      "POB": "Nyack",
      "YOB": 1882,
      "YOD": 1967,
      "POD": "Washington Square North",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0805a Paul Guilaume (various) - Amedeo Modigliani.jpg'",
      "Title": "",
      "Artist": "Amedeo Modigliani",
      "Nationality": "Italian",
      "POB": "Livorno",
      "YOB": 1884,
      "YOD": 1920,
      "POD": "Saint-Étienne",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0901 Heritage - Cai Guo-Qiang.jpg'",
      "Title": "",
      "Artist": "Cai Guo-Qiang",
      "Nationality": "Chinese",
      "POB": "Quanzhou",
      "YOB": 1957,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0902 Spirit of the Plains - Sydney Long.jpg'",
      "Title": "",
      "Artist": "Sydney Long",
      "Nationality": "Australian",
      "POB": "Goulburn",
      "YOB": 1871,
      "YOD": 1955,
      "POD": "London",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0903 Bonnie Sue 1964 - Margaret Olley.jpg'",
      "Title": "",
      "Artist": "Margaret Olley",
      "Nationality": "Australian",
      "POB": "Lismore",
      "YOB": 1923,
      "YOD": 2011,
      "POD": "Paddington",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0904 Nude women reading - Robert Delaunay.jpg'",
      "Title": "",
      "Artist": "Robert Delaunay",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1885,
      "YOD": 1941,
      "POD": "Montpellier",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'0905 Las Meninas - Diego VelÃ¡zquez.jpg'",
      "Title": "",
      "Artist": "Diego Velázquez",
      "Nationality": "Spanish",
      "POB": "Seville",
      "YOB": 1599,
      "YOD": 1660,
      "POD": "Madrid",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1001 Preparing to go out - Taniguchi Fumie.jpg'",
      "Title": "",
      "Artist": "Fumie Taniguchi",
      "Nationality": "Japanese",
      "POB": "Tokyo",
      "YOB": 1910,
      "YOD": 2001,
      "POD": "Los Angeles",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": "https://www.ngv.vic.gov.au/essay/rediscovering-fumie-taniguchi/"
    },
    {
      "Art": "'1002 Self-portrait with Model - Ernest Ludwig Kirchner.jpg'",
      "Title": "",
      "Artist": "Ernest Ludwig Kirchner",
      "Nationality": "German",
      "POB": "Aschaffenburg",
      "YOB": 1880,
      "YOD": 1938,
      "POD": "Frauenkirch",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1003 Yellow Red Blue - Wassily Kandinsky.jpg'",
      "Title": "",
      "Artist": "Wassily Kandinsky",
      "Nationality": "Russian",
      "POB": "Moscow",
      "YOB": 1866,
      "YOD": 1944,
      "POD": "Neuilly-sur-Seine",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1004 Portrait of Dora Mara - Pablo Picasso.jpg'",
      "Title": "",
      "Artist": "Pablo Picasso",
      "Nationality": "Spanish",
      "POB": "Málaga",
      "YOB": 1881,
      "YOD": 1973,
      "POD": "Mougins",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1005 Boulevard Montmartre, matin, temps gris - Camille Pissarro.jpg'",
      "Title": "",
      "Artist": "Camille Pissarro",
      "Nationality": "Danish-French",
      "POB": "Charlotte Amalie",
      "YOB": 1830,
      "YOD": 1903,
      "POD": "Paris",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1101 Actual Fractual - Howard Arkley.jpg'",
      "Title": "",
      "Artist": "Howard Arkley",
      "Nationality": "Australian",
      "POB": "Melbourne",
      "YOB": 1951,
      "YOD": 1999,
      "POD": "Mebourne",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1102 The Hunters in the Snow - Peter Bruegel.jpg'",
      "Title": "",
      "Artist": "Pieter Bruegel the Elder",
      "Nationality": "Dutch",
      "POB": "Breda or Breugel",
      "YOB": "c. 1525-1530",
      "YOD": 1569,
      "POD": "Brussels",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1103 Tiger in a Tropical Storm - Henri Rousseau.jpg'",
      "Title": "",
      "Artist": "Henri Rousseau",
      "Nationality": "French",
      "POB": "Laval",
      "YOB": 1844,
      "YOD": 1910,
      "POD": "Paris",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1104 Haystack in the morning - Claude Monet.jpg'",
      "Title": "",
      "Artist": "Claude Monet",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1840,
      "YOD": 1926,
      "POD": "Giverny",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1105 Brute Folly - Francisco Goya y Lucientes.jpg'",
      "Title": "",
      "Artist": "Francisco Goya",
      "Nationality": "Spanish",
      "POB": "Fuendetodos",
      "YOB": 1746,
      "YOD": 1828,
      "POD": "Bordeaux",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1201 Wax Dogs on Lake Eyre - Lin Onus.jpg'",
      "Title": "",
      "Artist": "Lin Onus",
      "Nationality": "Australian",
      "POB": "Boroondara",
      "YOB": 1948,
      "YOD": 1996,
      "POD": "Naarm",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": "https://www.artgallery.nsw.gov.au/collection/artists/onus-lin/"
    },
    {
      "Art": "'1202 Summertime - Mary Cassatt.png'",
      "Title": "",
      "Artist": "Mary Cassat",
      "Nationality": "American",
      "POB": "Allegheny",
      "YOB": 1844,
      "YOD": 1926,
      "POD": "Château de Beaufresne",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1203 Bal du moulin de la Galette - Pierre-Auguste Renoir.jpg'",
      "Title": "",
      "Artist": "Pierre-Auguste Renoir",
      "Nationality": "French",
      "POB": "Limoges",
      "YOB": 1841,
      "YOD": 1919,
      "POD": "Cagnes-sur-Mer",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1301 Untitled (Dog) - Keith Harring.jpg'",
      "Title": "",
      "Artist": "Keith Harring",
      "Nationality": "American",
      "POB": "Reading",
      "YOB": 1958,
      "YOD": 1990,
      "POD": "New York",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1302 Ideas of Barak - Vernon Ah Kee.jpg'",
      "Title": "",
      "Artist": "Vernon Ah Kee",
      "Nationality": "Australian",
      "POB": "Innisfail",
      "YOB": 1967,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": "https://www.ngv.vic.gov.au/multimedia/vernon-ah-kee-investigating-ideas-of-barak/"
    },
    {
      "Art": "'1303 Number 6 - Jackson Pollock.jpg'",
      "Title": "",
      "Artist": "Jackson Pollock",
      "Nationality": "American",
      "POB": "Cody",
      "YOB": 1912,
      "YOD": 1956,
      "POD": "Springs",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1304 When Will You Marry - Paul Gauguin.jpg'",
      "Title": "",
      "Artist": "Paul Gaugin",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1848,
      "YOD": 1903,
      "POD": "Atuona",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1305 Tea and coffee salon, Saba - Saeki Shunko.jpg'",
      "Title": "Tea and coffee salon, Sabō",
      "Artist": "Saeki Shunko",
      "Nationality": "Japanese",
      "POB": "Toyama Prefecture",
      "YOB": 1909,
      "YOD": 1942,
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1306 The Son of Man - Rene Magritte.jpg'",
      "Title": "",
      "Artist": "Rene Magritte",
      "Nationality": "Belgian",
      "POB": "Lessines",
      "YOB": 1898,
      "YOD": 1967,
      "POD": "Rue des Mimosas",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1307 I am a Mermaid - Eunice DjerrkÅ‹u YunupiÅ‹u.jpg'",
      "Title": "I am a Mermaid",
      "Artist": "Djerrkŋu Yunupiŋu (Eunice)",
      "Nationality": "Australian",
      "POB": "Inglis Island",
      "YOB": "c.1945",
      "YOD": 2022,
      "POD": "Yirrkala",
      "Painting Date": 2020,
      "Medium": "Earth pigments and recycled print toner on Stringybark (Eucalyptus sp.)",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "This is my favourite one",
      "ExtraLink": "https://www.ngv.vic.gov.au/multimedia/djerrkngu-yunupingu-i-am-a-mermaid/"
    },
    {
      "Art": "'1401 Elephant Walking - Eadweard Muybridge.gif'",
      "Title": "",
      "Artist": "Eadweard Muybridge",
      "Nationality": "English",
      "POB": "Kingston upon Thames",
      "YOB": 1830,
      "YOD": 1904,
      "POD": "Kingston upon Thames",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1402 Mona Lisa - Leonardo da Vinci.jpg'",
      "Title": "",
      "Artist": "Leonardo da Vinci",
      "Nationality": "Italian",
      "POB": "Anchiano",
      "YOB": 1452,
      "YOD": 1519,
      "POD": "Château du Clos Lucé",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1403 Houses at Auvers - Vincent Van Gogh.jpg'",
      "Title": "",
      "Artist": "Vincent van Gogh",
      "Nationality": "Dutch",
      "POB": "Zundert",
      "YOB": 1853,
      "YOD": 1890,
      "POD": "Auvers-sur-Oise",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1404 The Banquet of Cleopatra - Giovanni Battista Tiepolo.jpg'",
      "Title": "",
      "Artist": "Giovanni Battista Tiepolo",
      "Nationality": "Italian",
      "POB": "Venice",
      "YOB": 1696,
      "YOD": 1770,
      "POD": "Madrid",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1405 Horses bathing in the sea - Lucy Kemp.jpg'",
      "Title": "",
      "Artist": "Lucy Kemp-Welch",
      "Nationality": "British",
      "POB": "Bournemouth",
      "YOB": 1869,
      "YOD": 1958,
      "POD": "Watford",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1501 The Persistance of Memory - Salvador Dali.jpg'",
      "Title": "",
      "Artist": "Salvador Dali",
      "Nationality": "Spanish",
      "POB": "Figueres",
      "YOB": 1904,
      "YOD": 1989,
      "POD": "Figueres",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1502 Dancers in Blue - Edgar Dagas.png'",
      "Title": "",
      "Artist": "Edgar Degas",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1834,
      "YOD": 1917,
      "POD": "Paris",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1503 Morning Sunlight on the Snow - Camille Pissarro.jpg'",
      "Title": "",
      "Artist": "Camille Pissarro",
      "Nationality": "Danish-French",
      "POB": "Charlotte Amalie",
      "YOB": 1830,
      "YOD": 1903,
      "POD": "Paris",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1504 Flying Cloud - Kenneth Macqueen.jpg'",
      "Title": "",
      "Artist": "Kenneth McQueen",
      "Nationality": "Australian",
      "POB": "",
      "YOB": 1897,
      "YOD": 1960,
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1505 The Water Lily Pond - Claude Monet.jpg'",
      "Title": "",
      "Artist": "Claude Monet",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1840,
      "YOD": 1926,
      "POD": "Giverny",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "1506 It's our destiny 2 - Eko Nugroho.jpg",
      "Title": "",
      "Artist": "Eko Nugroho",
      "Nationality": "Indonesian",
      "POB": "Yogyakarta",
      "YOB": 1977,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1507 Abstract Painting (725-3) - Gerhard Richter.jpg'",
      "Title": "",
      "Artist": "Gerhard Richter",
      "Nationality": "German",
      "POB": "Dresden",
      "YOB": 1932,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1601 Ham Long Street - Bui Xuan Phai.jpg'",
      "Title": "",
      "Artist": "Bùi Xuân Phái",
      "Nationality": "Vietnamese",
      "POB": "Hanoi",
      "YOB": 1920,
      "YOD": 1988,
      "POD": "Hanoi",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1602 Self-Portrait (1889) - Vincent Van Gogh.jpg'",
      "Title": "",
      "Artist": "Vincent van Gogh",
      "Nationality": "Dutch",
      "POB": "Zundert",
      "YOB": 1853,
      "YOD": 1890,
      "POD": "Auvers-sur-Oise",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1603 Dry Salvages - John Olsen.jpg'",
      "Title": "",
      "Artist": "John Olsen",
      "Nationality": "Australian",
      "POB": "Newcastle",
      "YOB": 1928,
      "YOD": 2023,
      "POD": "Bowrai",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1604 The Lacquer Room - Grace Cossington Smith.jpg'",
      "Title": "",
      "Artist": "Grace Cossington Smith",
      "Nationality": "Australian",
      "POB": "Neutral Bay",
      "YOB": 1892,
      "YOD": 1984,
      "POD": "Roseville",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1605 Jet Stream - Julian Opie.jpg'",
      "Title": "",
      "Artist": "Julian Opie",
      "Nationality": "British",
      "POB": "London",
      "YOB": 1958,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1606 Meadow with Poplars - Claude Monet.jpg'",
      "Title": "",
      "Artist": "Claude Monet",
      "Nationality": "French",
      "POB": "Paris",
      "YOB": 1840,
      "YOD": 1926,
      "POD": "Giverny",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1701 Monday Morning - Vida Lahey.jpg'",
      "Title": "",
      "Artist": "Vida Lahey",
      "Nationality": "Australian",
      "POB": "Pimpama",
      "YOB": 1882,
      "YOD": 1968,
      "POD": "Wonga",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1702 Woman in an Armchair - Pablo Picasso.png'",
      "Title": "",
      "Artist": "Pablo Picasso",
      "Nationality": "Spanish",
      "POB": "Málaga",
      "YOB": 1881,
      "YOD": 1973,
      "POD": "Mougins",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1703 A Scene on the Ice near a Town - Hendrick Avercamp.jpg'",
      "Title": "",
      "Artist": "Hendrick Avercamp",
      "Nationality": "Dutch",
      "POB": "Amsterdam",
      "YOB": 1585,
      "YOD": 1634,
      "POD": "Kampen",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1704 Apples and Oranges - Paul CÃ©zanne.jpg'",
      "Title": "",
      "Artist": "Paul Cézanne",
      "Nationality": "French",
      "POB": "Aix-en-Provence",
      "YOB": 1839,
      "YOD": 1906,
      "POD": "Aix-en-Provence",
      "Painting Date": 1900,
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1801 Against all odds - Brook Andrew.jpg'",
      "Title": "",
      "Artist": "Brook Andrew",
      "Nationality": "Australian",
      "POB": "Sydney",
      "YOB": 1970,
      "YOD": "Present",
      "POD": "",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1802 Horseman in Landscape - Fred Williams.jpg'",
      "Title": "",
      "Artist": "Fred Williams",
      "Nationality": "Australian",
      "POB": "Richmond",
      "YOB": 1927,
      "YOD": 1982,
      "POD": "Hawthorn",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1803 Mortaruru with red overhead - Aleksandr Volkov.png'",
      "Title": "",
      "Artist": "Alexander Nikolaevich Volkov",
      "Nationality": "Russian",
      "POB": "Fergana",
      "YOB": 1886,
      "YOD": 1957,
      "POD": "Tashkent",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1804 A lion attacking a horse - George Stubbs.jpg'",
      "Title": "",
      "Artist": "George Stubbs",
      "Nationality": "English",
      "POB": "Liverpool",
      "YOB": 1724,
      "YOD": 1806,
      "POD": "Marylebone",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1805 Man in blue )maybe.... - Pablo Picasso.jpg'",
      "Title": "",
      "Artist": "Pablo Picasso",
      "Nationality": "Spanish",
      "POB": "Málaga",
      "YOB": 1881,
      "YOD": 1973,
      "POD": "Mougins",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    },
    {
      "Art": "'1806 Spring Scene - Rupert Bunny.jpg'",
      "Title": "",
      "Artist": "Rupert Bunny",
      "Nationality": "Australian",
      "POB": "Melbourne",
      "YOB": 1864,
      "YOD": 1947,
      "POD": "Melbourne",
      "Painting Date": "",
      "Medium": "",
      "Style": "",
      "Genre": "",
      "Period": "",
      "Comment": "",
      "ExtraLink": ""
    }
  ]
    */