  var small_images  = document.getElementsByClassName("small-image");
  var show_image_popup  = document.getElementById("show_image_popup");
  var large_image  = document.getElementById("large-image");
  var close_btn = document.getElementById("close-btn");
  
  document.getElementById('svg_file').addEventListener('load', function() {
    var svgDoc = this.contentDocument; // Access the SVG document inside <object>
    var images = svgDoc.querySelectorAll('image'); // Get all <image> elements

    images.forEach(function(image) {
      image.addEventListener('click', function() {
        // Handle the click event
        var id_of_painting = image.getAttribute('id');
        display_popup_from_svg(id_of_painting);
      })})});
        
  
function display_popup_from_svg(id_of_painting){
  if (id_of_painting == '1401_ElephantWalking_EadweardMuybridge'){
    var filepath='images/individual_art/'+id_of_painting+'.gif'  
  } else if(id_of_painting=='1502_DancersInBlue_EdgarDagas'){
    var filepath='images/individual_art/'+id_of_painting+'.png'      
  } else{
  var filepath='images/individual_art/'+id_of_painting+'.jpg'
  };
  large_image.src=filepath

  var artistString = '<em>'+artData[id_of_painting]["artist"]+'</em>'+' ('+artData[id_of_painting]['nationality']+', '+artData[id_of_painting]['yob']+'-'+artData[id_of_painting]['yod']+')';
  var titleString = '<i><b>'+artData[id_of_painting]['title']+',</i></b>'+' '+artData[id_of_painting]['paintingDate'];
  var mediumString = artData[id_of_painting]['medium'];
  var commentString = artData[id_of_painting]['comment']+'<br>For more information please visit <a href='+artData[id_of_painting]["extraLink"]+'> this site</a>.';
  
  
  document.getElementById("title").innerHTML = titleString;
  document.getElementById("artist").innerHTML = artistString;
  document.getElementById('medium').innerHTML = mediumString;
  document.getElementById('comment').innerHTML = commentString;
  showModal();
}
  
  function showModal(){
    show_image_popup.style.display = 'block';
  }
  
  close_btn.addEventListener("click", function(){
    show_image_popup.style.display = 'none';
  });
  


  //writing in all the artData, there must be a cleaner way to do this. JS is so janky

  let artData = {
    "0101_Pity_WilliamBlake":{
      "art": "0101_Pity_WilliamBlake",
      "title": "Pity",
      "artist": "William Blake",
      "nationality": "English",
      "pob": "Soho",
      "yob": 1757,
      "yod": 1827,
      "pod": "London",
      "paintingDate": "c. 1795",
      "medium": "Colour print, finished in ink and watercolour, on paper",
      "style": "Romanticism?",
      "genre": "",
      "period": "",
      "comment": "This artwork is a literal illustration of a double simile from <i>Macbeth</i>, found in the lines: <blockquote>And pity, like a naked new-born babe,\nStriding the blast, or heaven's cherubim, hors'd\nUpon the sightless couriers of the air.\n- Macbeth (1.7.21–23)</blockquote>",
      "extraLink": "https://www.metmuseum.org/art/collection/search/347416"
    },
    '0102_TheBattleOfSanRomano_PaoloUccello':{
      "art": "0102_TheBattleOfSanRomano_PaoloUccello",
      "title": "The Battle of San Romano",
      "artist": "Paolo Uccello",
      "nationality": "Italian",
      "pob": "Pratovecchio",
      "yob": 1397,
      "yod": 1475,
      "pod": "Florence",
      "paintingDate": "c. 1438-1440",
      "medium": "Egg tempera with walnut oil and linseed oil on poplar",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The Battle of San Romano is a set of three paintings by the Florentine painter Paolo Uccello depicting events that took place at the Battle of San Romano between Florentine and Sienese forces in 1432. Each of them are like three meters long, so much bigger than what you are looking at here. Heartbreakingly, all three pieces are divided between three collections, the National Gallery, London, the Galleria degli Uffizi, Florence, and the Musée du Louvre, Paris.",
      "extraLink": "https://www.beyondtheyalladog.com/2013/08/the-battle-of-san-romano-in-separate-pieces/"
    },
    '0103_TwoWomen_MaryCockburnMercer':{
      "art": "0103_TwoWomen_MaryCockburnMercer",
      "title": "(Two women)",
      "artist": "Mary Cockburn Mercer",
      "nationality": "Australian",
      "pob": "Scotland",
      "yob": 1882,
      "yod": 1963,
      "pod": "Aubagne",
      "paintingDate": "c. 1940",
      "medium": "Watercolour over pencil on buff paper",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Mary Cockburn Mercer, was an Australian painter. She spent the 1920s and 1930s in Europe, and the 1940s in Melbourne, Australia. Her final years were spent in France. She exhibited with the Contemporary Art Society in Australia. This painting is of two close friends hanging out.",
      "extraLink": "https://www.ngv.vic.gov.au/custom/screens/josephbrown/index.php?artistid=14217&chapter=3"
    },
    '0201_MotherAndChild1907_PabloPicasso':{
      "art": "0201_MotherAndChild1907_PabloPicasso",
      "title": "Mother and child",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": 1907,
      "medium": "Oil on canvas",
      "style": "Cubism",
      "genre": "",
      "period": "",
      "comment": "This is classic Picasso. See how the faces don't look like faces but they feel like faces? Classic Picasso. This is one of many paintings by Picasso depicting a mother and child. So, I don't know if he had a weird Freud thing going on, or just lived the subject matter. It also made hunting down this particular mother and child quite difficult. So, you're welcome.",
      "extraLink": "https://arthive.com/pablopicasso/works/376118~Mother_and_child"
    },
    "0202_IfNotNo_RonaldBrooksKitaj":{
      "art": "0202_IfNotNo_RonaldBrooksKitaj",
      "title": "If Not, Not",
      "artist": "Robert Brooks Kitaj",
      "nationality": "American",
      "pob": "Chagrin Falls",
      "yob": 1932,
      "yod": 2007,
      "pod": "Los Angeles",
      "paintingDate": "1975-1976",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Believe it or not, this is a self-portrait. The artist is the one holding the baby in bed. This piece also makes many references to TS Elliot's poem <i>The Waste Land</i>. I think it is about the holocaust? The artist is Jewish and has a few pieces exploring that subject. Also, great name for a painting.",
      "extraLink": "https://www.nationalgalleries.org/art-and-artists/644/if-not-not"
    },
    "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid":{
      "art": "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid",
      "title": "Q",
      "artist": "David McDiarmid",
      "nationality": "Australian",
      "pob": "Hobart",
      "yob": 1952,
      "yod": 1995,
      "pod": "Sydney",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "So this one is a bit hard to pin down. There was a Rainbow Aphorism series and this one is one of them. David MacDiarmid was an artist, designer, and political activist, recognised for his prominent and sustained artistic engagement in issues relating to gay male identity and HIV/AIDS. He is also known for his involvement in the gay liberation movement of the early 1970s, when he was the first person arrested at a gay rights protest in Australia, as well as his artistic direction of the Sydney Gay and Lesbian Mardi Gras. From its inception, McDiarmid's art career encompassed, as both subject and inspiration, gay male sexuality, politics, and urban subcultures.",
      "extraLink": "https://fabricquarterly.com.au/2020/10/i-want-a-future-that-lives-up-to-my-past-david-mcdiarmid-and-local-queer-stories/"
    },
    "0204_GreatStillLifeOnPedestal_PabloPicasso":{
      "art": "0204_GreatStillLifeOnPedestal_PabloPicasso",
      "title": "Still Life on a Pedestal Table",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": 1931,
      "medium": "Oil on canvas",
      "style": "Surrealism",
      "genre": "Still life",
      "period": "Neoclassicist & Surrealist Period",
      "comment": "Another Picasso but this one is surreal instead of a bunch of cubes. I sort of see a dog in there if I squint 🤷. What do you see? When you come out of the toilet mention it to us!",
      "extraLink": "https://arthive.com/pablopicasso/works/619569~Still_Life_on_a_Pedestal_Table"
    },
    "0205_RembrandtSelf-PortraitWithTwoCircles_Rembrandt":{
      "art": "0205_RembrandtSelf-PortraitWithTwoCircles_Rembrandt",
      "title": "Self-Portrait with Two Circles",
      "artist": "Rembrandt Harmenszoon van Rijn",
      "nationality": "Dutch",
      "pob": "Leiden",
      "yob": 1606,
      "yod": 1669,
      "pod": "Amsterdam",
      "paintingDate": 1665,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at this absolute beast of a painter smashing together this self-portrait. The self-assured grin. He knows he is considered a master in his art. And then just to flex he throws in two perfectly drawn circles. Because why not?",
      "extraLink": "https://www.rembrandtpaintings.com/self-portrait-with-two-circle.jsp"
    },
    "0206_PankASquith":{
      "art": "0206_PankASquith",
      "title": "Pank-a-Squith",
      "artist": "British Women's Social and Political Union",
      "nationality": "British",
      "pob": "-",
      "yob": "1903",
      "yod": "1918",
      "pod": "-",
      "paintingDate": "c. 1909",
      "medium": "Ink on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Roll on up and roll the dice because this one is a board game! Pank-a-Squith was a political board game about the suffragette movement created around 1909. It was created for the British Women's Social and Political Union to generate funds and help spread women's suffrage ideologies. You roll the dice to move the women closer to Parliament house. Thankfully this is now over a century old and a thing of the past.",
      "extraLink": "https://boardgamegeek.com/boardgame/14249/pank-squith"
    },
    "0207_LamentationTheMourningOfChrist_Giotto":{
      "art": "0207_LamentationTheMourningOfChrist_Giotto",
      "title": "Lamentation (The Mourning of Christ)",
      "artist": "Giotto di Bondone",
      "nationality": "Italian",
      "pob": "Florence",
      "yob": 1267,
      "yod": 1337,
      "pod": "Florence",
      "paintingDate": "c. 1304-1306",
      "medium": "Fresco",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Lamentation (The Mourning of Christ) is a fresco painted c.1305 by the Italian artist Giotto as part of his cycle of the Life of Christ on the interior walls of the Scrovegni Chapel in Padua, Italy. In the painting, the body of the crucified Christ has been lowered from the cross and laid on the ground, surrounded by his grieving mother and disciples. His head is held by Mary, his mother, and his feet by Mary Magdelene. John the Apostle throws his arms wide in despair. To the right, Nicodemus and Joseph of Arimathea wait to prepare the body to be laid in a tomb.",
      "extraLink": "https://www.thehistoryofart.org/giotto/lamentation/"
    },
    "0301_Primavera_SandroBotticelli":{
      "art": "0301_Primavera_SandroBotticelli",
      "title": "Primavera",
      "artist": "Sandro Botticelli",
      "nationality": "Italian",
      "pob": "Florence",
      "yob": 1445,
      "yod": 1510,
      "pod": "Florence",
      "paintingDate": "",
      "medium": "Tempera on large panel",
      "style": "Renaissance/Mythological Scene",
      "genre": "",
      "period": "",
      "comment": "You better believe this painting is depicting the Realm of Venus. Zephyr chases the nymph Chloris, who turns into the goddess Flora on the right. Venus is underneath a blindfolded cupid in flight with the three Graces and Mercury on the left.",
      "extraLink": "https://news.artnet.com/art-world/sandro-botticelli-primavera-4-things-to-know-1937013"
    },
    "0302_LittleThuy":{
      "art": "0302_LittleThuy",
      "title": "Little Thuy",
      "artist": "Trần Văn Cẩn",
      "nationality": "Vietnamese",
      "pob": "Kiến An",
      "yob": 1910,
      "yod": 1994,
      "pod": "Hanoi",
      "paintingDate": 1943,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The character in the picture is Minh Thuy, the niece of the painter. it was painted in 1943, a few years before the August revolution against the French and Japanese colonial rule. Thuy is still alive (as of 2022), living with her children and grandchildren.",
      "extraLink": "https://e.vnexpress.net/news/culture/restoring-national-painting-treasure-little-thuy-a-labor-of-love-4490256.html"
    },
    "0303_TheScream_EdvardMunch":{
      "art": "0303_TheScream_EdvardMunch",
      "title": "The Scream",
      "artist": "Edvard Munch",
      "nationality": "Norwegian",
      "pob": "Adalsbruk",
      "yob": 1863,
      "yod": 1944,
      "pod": "Oslo",
      "paintingDate": 1893,
      "medium": "Oil, tempera, and pastel on cardboard",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "What a piece. The artist describes the inspiration for this image thusly: \"I was walking along the road with two friends – the sun was setting – suddenly the sky turned blood red – I paused, feeling exhausted, and leaned on the fence – there was blood and tongues of fire above the blue-black fjord and the city – my friends walked on, and I stood there trembling with anxiety – and I sensed an infinite scream passing through nature.\" 😱😱😱",
      "extraLink": "https://www.edvardmunch.org/the-scream.jsp"
    },
    "0304_TheRhinoceros_Albrecht":{
      "art": "0304_TheRhinoceros_Albrecht",
      "title": "The Rhinocerus",
      "artist": "Albrecht Dürer",
      "nationality": "German",
      "pob": "Nuremberg",
      "yob": 1471,
      "yod": 1528,
      "pod": "Nuremberg",
      "paintingDate": 1515,
      "medium": "Woodcut",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a woodcut of a rhinoceros that the artist never saw. Instead, this woodcut is based on an anonymous written description and brief sketch of an Indian rhinoceros brought to Lisbon in 1515. The rhinoceros in question subsequently died at sea when the King sent it to the Pope as a gift. There is a German inscription on the woodcut that reads: <br>\"On the first of May in the year 1513 AD [sic], the powerful King of Portugal, Manuel of Lisbon, brought such a living animal from India, called the rhinoceros. This is an accurate representation. It is the colour of a speckled tortoise, and is almost entirely covered with thick scales. It is the size of an elephant but has shorter legs and is almost invulnerable. It has a strong pointed horn on the tip of its nose, which it sharpens on stones. It is the mortal enemy of the elephant. The elephant is afraid of the rhinoceros, for, when they meet, the rhinoceros charges with its head between its front legs and rips open the elephant's stomach, against which the elephant is unable to defend itself. The rhinoceros is so well-armed that the elephant cannot harm it. It is said that the rhinoceros is fast, impetuous, and cunning.",
      "extraLink": "https://www.rct.uk/collection/800198/a-rhinoceros"
    },
    "0305_ThePreciousBook_GwenJohn":{
      "art": "0305_ThePreciousBook_GwenJohn",
      "title": "The Precious Book",
      "artist": "Gwen John",
      "nationality": "Welsh",
      "pob": "Haverfordwest",
      "yob": 1876,
      "yod": 1939,
      "pod": "Dieppe",
      "paintingDate": "c. 1916-1926",
      "medium": "Oil on cavas laid on panel",
      "style": "Post-Impressionisim",
      "genre": "",
      "period": "",
      "comment": "I couldn't find much information on this piece, only that it is now in the public domain. She is holding the book with a handkerchief, I suppose that makes the book precious.",
      "extraLink": "https://www.wikiart.org/en/gwen-john/the-precious-book"
    },
    "0306_WomenAndBirdInTheMoonlight_JoanMiro":{
      "art": "0306_WomenAndBirdInTheMoonlight_JoanMiro",
      "title": "Women and Bird in the Moonlight",
      "artist": "Joan Miró",
      "nationality": "Spanish",
      "pob": "Barcelona",
      "yob": 1893,
      "yod": 1983,
      "pod": "Palma",
      "paintingDate": 1949,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "How does this speak to you? What does it say? A seemingly bundle of shapes at first - but there is a moon. There are human shapes. The colours are nice.",
      "extraLink": "https://www.tate.org.uk/art/artworks/miro-women-and-bird-in-the-moonlight-n06007"
    },
    "0307_DanteRunningFromTheThreeBeasts_WilliamBlake":{
      "art": "0307_DanteRunningFromTheThreeBeasts_WilliamBlake",
      "title": "Dante running from the Three Beasts",
      "artist": "William Blake",
      "nationality": "English",
      "pob": "Soho",
      "yob": 1757,
      "yod": 1827,
      "pod": "London",
      "paintingDate": "1824-1827",
      "medium": "Pen and ink and watercolour over pencil and black chalk",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Three beasts walk into a bar and Dante runs away. This is Blake illustrating the Divine Comedy (the one with the circles of hell). So, technically a very early version of fan art. Dante looks like he is in Warrior 2.",
      "extraLink": "https://artsandculture.google.com/asset/dante-running-from-the-three-beasts-william-blake/-wEF4rg1T7H2JA?hl=en"
    },
    "0401_TheGreatWave_KatsushikaHokusai":{
      "art": "0401_TheGreatWave_KatsushikaHokusai",
      "title": "The Great Wave off Kanagawa",
      "artist": "Katasushika Hokusai",
      "nationality": "Japanese",
      "pob": "Edo",
      "yob": 1760,
      "yod": 1849,
      "pod": "Tokyo",
      "paintingDate": 1831,
      "medium": "Ukiyo-e (Woodblock print)",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I got a coffee mug with this image on it. It is a beautiful piece and has been parodied and been an influence for many works throughout the ages. This is a part of a series of other artworks depicting Fuji-Yama and sure enough, Fuji-Yama is at the back, capped in snow. As Japanese read right to left one can argue that the proper way to view this image is to invert it. Doing so makes the wave feel more dangerous, as if it will crush the boat.",
      "extraLink": "https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa"
    },
    "0501_Ophelia_JohnEverettMillais":{
      "art": "0501_Ophelia_JohnEverettMillais",
      "title": "Ophelia",
      "artist": "John Everett Millais",
      "nationality": "English",
      "pob": "Southampton",
      "yob": 1829,
      "yod": 1896,
      "pod": "Kensington",
      "paintingDate": "1851-1852",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Imagine being Ophelia, fully clothed and just absolutely drenched in water. You better have hoped it was a hot day because my word I would be miserable if it was anything less than 40 degrees. It is a painting depicting <i>Hamlet</i>, Act IV, Scene vii where she oh... she falls into a stream and drowns.",
      "extraLink": "https://www.tate.org.uk/art/artworks/millais-ophelia-n01506"
    },
    "0502_Self-PortraitAsTheAllegoryOfPainting_ArtemisiaGentileschi":{
      "art": "0502_Self-PortraitAsTheAllegoryOfPainting_ArtemisiaGentileschi",
      "title": "Self-Portrait as the Allegory of Painting (La Pittura)",
      "artist": "Artemisia Gentileschi",
      "nationality": "Italian",
      "pob": "Rome",
      "yob": 1593,
      "yod": 1653,
      "pod": "Naples",
      "paintingDate": "1638-1639",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a classic self-portrait of an artist. Bonus points for the artist painting another painting in the painting. In fact, she is depicting herself as the female personification of Painting, but in a tongue in cheek way I think?",
      "extraLink": "https://www.rct.uk/collection/405551/self-portrait-as-the-allegory-of-painting-la-pittura"
    },
    "0503_Self-PortraitWithThornNecklaceAndHummingbird_FridaKahlo":{
      "art": "0503_Self-PortraitWithThornNecklaceAndHummingbird_FridaKahlo",
      "title": "Self-Portrait with Thorn Necklace and Hummingbird",
      "artist": "Frida Kahlo",
      "nationality": "Mexican",
      "pob": "Coyoacán",
      "yob": 1907,
      "yod": 1954,
      "pod": "Coyoacán",
      "paintingDate": 1940,
      "medium": "Oil on canvas on masonite",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "It's Kahlo! There are some animals here as well all with their own symbolism associated with them. The hummingbird could symbolise freedom but now it is dead, or it could represent a good luck charm for falling in love or it is meant to invoke the Aztec god of war. The monkey is a symbol of evil, but also, she was gifted a spider monkey from Rivera whom she had just divorced. The thorns, is it meant to be Christ like or just ouchy ouchy? Don't think about these things too hard. Just look at the pretty animals.",
      "extraLink": "https://www.fridakahlo.org/self-portrait-with-thorn-necklace-and-hummingbird.jsp"
    },
    "0504_LeGrandCanal_ClaudeMonet":{
      "art": "0504_LeGrandCanal_ClaudeMonet",
      "title": "Le Grand Canal",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": 1908,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "<i>Le Grand Canal</i> (or <i>The Grand Canal</i> in english) is one of six paintings looking down the canal towards the Salute Church. It is sort of like Magic: The Gathering where you have alternative art of the same card. It sold for $35 million in 2015. Here you can see it in the Toilet Gallery completely free of charge.",
      "extraLink": "https://en.wikipedia.org/wiki/Le_Grand_Canal"
    },
    "0505_TheKiss_GustavKlimt":{
      "art": "0505_TheKiss_GustavKlimt",
      "title": "The Kiss",
      "artist": "Gustav Klimt",
      "nationality": "Austrian",
      "pob": "Baumgarten",
      "yob": 1862,
      "yod": 1918,
      "pod": "Vienna",
      "paintingDate": "1907-1908",
      "medium": "Oil and gold leaf on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a classic piece. It was hailed as pornographic at the time of its unveiling. Actual gold leaf was used in it as well. Not in this postcard though, so please don't steal it.",
      "extraLink": "https://www.gustav-klimt.com/The-Kiss.jsp"
    },
    "0506_ArnolfiniPortrait_VanEyck":{
      "art": "0506_ArnolfiniPortrait_VanEyck",
      "title": "Arnolfini Portrait",
      "artist": "Jan van Eyck",
      "nationality": "Netherlandish",
      "pob": "Maaseik",
      "yob": 1390,
      "yod": 1441,
      "pod": "Bruges",
      "paintingDate": 1434,
      "medium": "Oil on oak panel of 3 vertical boards",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Hey check it out, it is Italian merchant Giovanni di Nicolao Arnolfini and his wife (no name). What a wonderful time for both capitalism and the patriarchy! The artist is flexing with the concave mirror in the background and they also threw in a cute little dog for good measure.",
      "extraLink": "https://en.wikipedia.org/wiki/Arnolfini_Portrait"
    },
    "0507_SexyRobot_HajimeSorayama":{
      "art": "0507_SexyRobot_HajimeSorayama",
      "title": "Robot",
      "artist": "Hajime Sorayama",
      "nationality": "Japanese",
      "pob": "Ehime",
      "yob": 1947,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "BEEP BOOP. HELLO HUMAN. I AM A SEXY ROBOT. LOOK AT MY SEXY RING. BEEP BOOP.",
      "extraLink": ""
    },
    "0601_ArtDeco1930s":{
      "art": "0601_ArtDeco1930s",
      "title": "Art, Goût, Beauté",
      "artist": "Art, Goût, Beauté",
      "nationality": "French",
      "pob": "-",
      "yob": "1921",
      "yod": "1933",
      "pod": "-",
      "paintingDate": "c.1921-1933",
      "medium": "Stencil",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This drawing is from the French fashion magazine <i>Art, Goût, Beauté</i>. It ran from 1921 to 1933 and its audience were the more upper class, as it gave hints and tips on how to dress, where to go, and how to behave. I am not sure who drew this piece, or indeed, which issue it appears in, the internet was sorely lacking on this topic.",
      "extraLink": "https://fashionsummedup.com/2021/05/02/art-gout-beaute/"
    },
    "0602_Bathers_RupertBunny":{
      "art": "0602_Bathers_RupertBunny",
      "title": "Bathers",
      "artist": "Rupert Bunny",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1864,
      "yod": 1947,
      "pod": "Melbourne",
      "paintingDate": 1906,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Ah, this is the Edwardian life baby. Nothing like hitting up the old salon and just chilling with the gals, ciggy in hand and clothes optional. Make public baths great again.",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/bathers/"
    },
    "0603_SorrowOfTheKing_HenriMatisse":{
      "art": "0603_SorrowOfTheKing_HenriMatisse",
      "title": "Sorrow of the King",
      "artist": "Henri Matisse",
      "nationality": "French",
      "pob": "Le Cateau-Cambrésis",
      "yob": 1869,
      "yod": 1954,
      "pod": "France",
      "paintingDate": 1952,
      "medium": "Gouache on paper on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "'Ooooh, I'm the king and I'm sad', is what I imagine the art is saying. This is Henri Matisse's last self-portrait. He was in poor health and by the 1950s we had given up painting in favour of creating these collages.",
      "extraLink": "https://www.henrimatisse.org/sorrow-of-the-king.jsp"
    },
    "0604_WilliamAndShirleyFloraAndFauna":{
      "art": "0604_WilliamAndShirleyFloraAndFauna",
      "title": "William and Shirley, flora and fauna 1985",
      "artist": "William Robinson",
      "nationality": "Australian",
      "pob": "Brisbane",
      "yob": 1936,
      "yod": "Present",
      "pod": "",
      "paintingDate": 1985,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at this cute little painting. I got nothing. It is cute!",
      "extraLink": "https://www.artlink.com.au/articles/2555/light-years-william-robinson-and-the-creation-stor/"
    },
    "0701_ForestCunninghamsGap_ConradMartens":{
      "art": "0701_ForestCunninghamsGap_ConradMartens",
      "title": "Forest, Cunningham's Gap",
      "artist": "Conrad Martens",
      "nationality": "English",
      "pob": "London",
      "yob": 1801,
      "yod": 1878,
      "pod": "North Sydney",
      "paintingDate": 1856,
      "medium": "Watercolour on paper",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "British-born Conrad Martens settled in Sydney in 1835 and established a lucrative career. Fifteen years later, however, New South Wales suffered an economic downturn and Martens visited the Moreton Bay area in the hope of obtaining commissions from his connections on the rich pastoral lands of the Darling Downs.\nMartens landed in Brisbane on 17 November 1851, and by 11 December was traversing the steep incline of Cunningham's Gap. This route, the most direct and picturesque from the coast, was also very hazardous. Here Martens, like travellers today, experienced a dramatic contrast between the dense rainforest surrounding Cunningham's Gap and the bright, open Downs.\nThe dark, oppressive scene he records is indicative of the way early settlers regarded the Australian bush. The novelist Marcus Clarke later described the Australian landscape as primitive and frightening, the untamed opposite of the English pastoral ideal.\nThe man on horseback is probably Martens himself on one of his two journeys through the area. The figure functions as a symbol of endeavour, about to break through the obscuring bush into the light of a new life.",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/forest-cunninghams-gap/"
    },
    "0702_Untitled1982_JeanMichelBasquiat":{
      "art": "0702_Untitled1982_JeanMichelBasquiat",
      "title": "Untitled (1982)",
      "artist": "Jean-Michel Basquiat",
      "nationality": "American",
      "pob": "New York",
      "yob": 1960,
      "yod": 1988,
      "pod": "New York",
      "paintingDate": 1982,
      "medium": "Acrylic, spray paint and oilstick on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a skeleton king! Fun fact, Basquiet has numerous artworks he has completed in 1982, most of them titled \"Untitled\" and one of them recently selling for $110 million dollars. So good luck finding anything on this other 1982 untitled piece. Honestly, the artist could have used a better naming convention.",
      "extraLink": "https://news.artnet.com/market/jean-michel-basquiat-most-expensive-works-2016-496796"
    },
    "0703_QueenslandNaive_JamesFardoulus":{
      "art": "0703_QueenslandNaive_JamesFardoulus",
      "title": "The start of Burke and Wills 1860",
      "artist": "James Fardoulys",
      "nationality": "Greek",
      "pob": "Kythera",
      "yob": 1900,
      "yod": 1975,
      "pod": "Brisbane (?)",
      "paintingDate": 1972,
      "medium": "Oil on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Burke and Wills were the first Europeans to cross Australia south to north. They set out in 1860 and finished in 1861. They then died on the return journey. but not all is lost, they expedition uncovered all this grazing land that the Europeans used to further their colonialism.",
      "extraLink": "https://www.qagoma.qld.gov.au/exhibition/james-fardoulys/"
    },
    "0704_GirlWithAPearlEarring_JohannesVermeer":{
      "art": "0704_GirlWithAPearlEarring_JohannesVermeer",
      "title": "Girl with a Pearl Earring",
      "artist": "Johannes Vermeer",
      "nationality": "Dutch",
      "pob": "Delft",
      "yob": 1632,
      "yod": 1675,
      "pod": "Delft",
      "paintingDate": "c.1665",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "She was a girl. Wearing an earring. Can I make it any more obvious? This is one of the all-time classics. I know one of the ai art generators was advertising itself by expanding out the borders of the painting. My personal favourite take on this piece is a Dutch astrophysicist who said, um actually the earring looks to be more polished tin on the grounds of the specular reflection, pear shape, and large size.",
      "extraLink": "https://en.m.wikipedia.org/wiki/Girl_with_a_Pearl_Earring"
    },
    "0705_BirdStealingBaby_SimonGende":{
      "art": "0705_BirdStealingBaby_SimonGende",
      "title": "Bird Stealing Baby",
      "artist": "Simon Gende",
      "nationality": "Paupa New Guinea",
      "pob": "Paupa New Guinean",
      "yob": 1969,
      "yod": "Present",
      "pod": "",
      "paintingDate": 2018,
      "medium": "Acrylic on cotton duck",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This piece is based off a PNG story where there are no men in a village so the bird goes and gets a baby from another place. And the new clan call him Pigeon. All the artists’ works continue the story (the link below is a wonderful YouTube video where he describes it all).",
      "extraLink": "https://youtu.be/o2pjPxaB5cg"
    },
    "0706_WaterLillies_ClaudeMonet":{
      "art": "0706_WaterLillies_ClaudeMonet",
      "title": "Water Lilies",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "1920-1926",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Monet loved nothing more than slinging out the paint and flipping together some water lilies. I mean, if you are good at what you do, but some variety would be nice. He painted a lot of these in the last 30 years of his life when he had cataracts which might explain why they're so splodgy.",
      "extraLink": "https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series)"
    },
    "0801_ASundayOnLaGrandeJatte_GeorgesSeurat":{
      "art": "0801_ASundayOnLaGrandeJatte_GeorgesSeurat",
      "title": "A Sunday on La Grande Jatte",
      "artist": "Gorges Seurat",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1859,
      "yod": 1891,
      "pod": "Paris",
      "paintingDate": 1884,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Although you may not think it, this painting is actually massive at 2x3m. I heavily recommend reading the link for the details on this piece because it is fascinating if just from a technical perspective. This artwork was painted with a technique known as Pointillism, basically the entire thing is made up of small uniform dots and our brains mix the colours that are close to each other.",
      "extraLink": "https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884"
    },
    "0802_TheFightingTemeraire_JosephMallordWilliamTurner":{
      "art": "0802_TheFightingTemeraire_JosephMallordWilliamTurner",
      "title": "The Fighting Temeraire",
      "artist": "Joseph Mallard William Turner",
      "nationality": "English",
      "pob": "Covent Garden",
      "yob": 1775,
      "yod": 1851,
      "pod": "Chelsea",
      "paintingDate": 1838,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at the lights, look at the colours. The full name of this piece is, <i>The Fighting Temeraire, tugged to her last berth to be broken up</i> which is too long to be snappy. It reminds me of the Elven ships sailing east - does it remind you of anything?",
      "extraLink": ""
    },
    "0803_StarryNight_VanGogh":{
      "art": "0803_StarryNight_VanGogh",
      "title": "The Starry Night",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "1889",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "As a part of year 10 English we had to listen to this song called Starry Starry Night and write about our feelings and how it was inspired by this painting. Coincidentally, this was also around the time that I grew disillusioned in English as a subject.",
      "extraLink": "https://www.youtube.com/watch?v=dipFMJckZOM"
    },
    "0804_Nighthawks_EdwardHopper":{
      "art": "0804_Nighthawks_EdwardHopper",
      "title": "Nighthawks",
      "artist": "Edward Hopper",
      "nationality": "American",
      "pob": "Nyack",
      "yob": 1882,
      "yod": 1967,
      "pod": "Washington Square North",
      "paintingDate": "1942",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Eeh see? We're just a couple of nighthawks hanging out at our favourite diner in Chicago, see? I'll have a large apple pie and milkshake, see? My favourite bit of trivia about this painting is Hopper's wife kept notes on all of Hopper's works. In it she says the intended name for the piece was originally <i>Night Hawks</i>. Is the actual name better? You decide. Perform a half flush for <i>Nighthawks</i> and a full flush for <i>Night Hawks</i>",
      "extraLink": "https://www.artic.edu/artworks/111628/nighthawks"
    },
    "0805a_PaulGuilaume_AmedeoModigliani":{
      "art": "0805a_PaulGuilaume_AmedeoModigliani",
      "title": "Paul Guillaume",
      "artist": "Amedeo Modigliani",
      "nationality": "Italian",
      "pob": "Livorno",
      "yob": 1884,
      "yod": 1920,
      "pod": "Saint-Étienne",
      "paintingDate": "c.1915",
      "medium": "Oil on cardboard probably",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "What an absolute trek it was to hunt this one down and, in the end, I didn't really achieve it fully. This piece is a portrait of Paul Guillaume by Modigliani but honestly, Modigliani churned these out for some reason. If you can find any more info that would be very helpful.",
      "extraLink": "https://www.ngv.vic.gov.au/orangerie/modiglianiimage.html"
    },
    "0901_Heritage_CaiGuo-Qiang":{
      "art": "0901_Heritage_CaiGuo-Qiang",
      "title": "Heritage",
      "artist": "Cai Guo-Qiang",
      "nationality": "Chinese",
      "pob": "Quanzhou",
      "yob": 1957,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2013",
      "medium": "Animals: polystyrene, gauze, resin and hide. Installed with artificial watering hole: water, sand, drip mechanism",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I know the image here doesn't match to the postcard in the physical Toilet Gallery. This image was taken from a different angle because it is a massive installation piece and not a painting. A single drop of water drums into the centre of the lake.",
      "extraLink": "https://blog.qagoma.qld.gov.au/cai-guo-qiang-heritage-99-replicas-of-animals/"
    },
    "0902_SpiritOfThePlains_SydneyLong":{
      "art": "0902_SpiritOfThePlains_SydneyLong",
      "title": "Spirit of the Plains",
      "artist": "Sydney Long",
      "nationality": "Australian",
      "pob": "Goulburn",
      "yob": 1871,
      "yod": 1955,
      "pod": "London",
      "paintingDate": "1897",
      "medium": "Oil on canvas on wood",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Naked lady leads weird Australian birds across the landscape.",
      "extraLink": "https://blog.qagoma.qld.gov.au/dancing-across-the-landscape-is-the-spirit-of-the-plains-sydney-long-australia/"
    },
    "0903_BonnieSue1964_MargaretOlley":{
      "art": "0903_BonnieSue1964_MargaretOlley",
      "title": "Bonnie Sue 1964",
      "artist": "Margaret Olley",
      "nationality": "Australian",
      "pob": "Lismore",
      "yob": 1923,
      "yod": 2011,
      "pod": "Paddington",
      "paintingDate": "1964",
      "medium": "Oil on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Jonah says that this one looks like Tabouli, and he's not far off. The painter loved her dog (Bonnie Sue) so much that she did a few paintings of them. I think we can all agree it is very aDOGable (instead of adorable).",
      "extraLink": "https://blog.qagoma.qld.gov.au/meet-bonnie-sue-margaret-olleys-beloved-pug/"
    },
    "0904_NudeWomenReading_RobertDelaunay":{
      "art": "0904_NudeWomenReading_RobertDelaunay",
      "title": "Nude Woman Reading",
      "artist": "Robert Delaunay",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1885,
      "yod": 1941,
      "pod": "Montpellier",
      "paintingDate": "1915",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Here we see a nude woman reading.",
      "extraLink": "https://artsandculture.google.com/asset/nude-woman-reading-robert-delaunay/-QFbKBNtET-twQ?hl=en"
    },
    "0905_LasMeninas_DiegoVelazquez":{
      "art": "0905_LasMeninas_DiegoVelázquez",
      "title": "Las Meninas",
      "artist": "Diego Velázquez",
      "nationality": "Spanish",
      "pob": "Seville",
      "yob": 1599,
      "yod": 1660,
      "pod": "Madrid",
      "paintingDate": "1656",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "If you feel judged while looking at this one, then I'm right there alongside you.",
      "extraLink": "https://www.britannica.com/topic/Las-meninas"
    },
    "1001_PreparingToGoOut_TaniguchiFumie":{
      "art": "1001_PreparingToGoOut_TaniguchiFumie",
      "title": "Preparing to go Out",
      "artist": "Fumie Taniguchi",
      "nationality": "Japanese",
      "pob": "Tokyo",
      "yob": 1910,
      "yod": 2001,
      "pod": "Los Angeles",
      "paintingDate": "1935",
      "medium": "six panel folding screen: ink, colour pigment on silk",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Just a couple of gals preparing to go out.",
      "extraLink": "https://www.ngv.vic.gov.au/essay/rediscovering-fumie-taniguchi/"
    },
    "1002_Self-portraitWithModel_ErnestLudwigKirchner":{
      "art": "1002_Self-portraitWithModel_ErnestLudwigKirchner",
      "title": "Self-portait with model",
      "artist": "Ernest Ludwig Kirchner",
      "nationality": "German",
      "pob": "Aschaffenburg",
      "yob": 1880,
      "yod": 1938,
      "pod": "Frauenkirch",
      "paintingDate": "c.1910",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Jeremy always thinks that this one looks like himself and Tara. Jeremy being the painter (inaccurate) and Tara being the attractive one (accurate).",
      "extraLink": "https://www.artchive.com/artwork/self-portrait-with-model-ernst-ludwig-kirchner-1910/"
    },
    "1003_YellowRedBlue_WassilyKandinsky":{
      "art": "1003_YellowRedBlue_WassilyKandinsky",
      "title": "Yellow-Red-Blue",
      "artist": "Wassily Kandinsky",
      "nationality": "Russian",
      "pob": "Moscow",
      "yob": 1866,
      "yod": 1944,
      "pod": "Neuilly-sur-Seine",
      "paintingDate": "1925",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This one screams music to me. It is what I imagine notes look like as they dance off the page and into an unsuspecting ear.",
      "extraLink": "https://www.wassily-kandinsky.org/Yellow-Red-Blue.jsp"
    },
    "1004_PortraitOfDoraMara_PabloPicasso":{
      "art": "1004_PortraitOfDoraMara_PabloPicasso",
      "title": "Portrait of Dora Maar",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "1937",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Who is Dora Maar? The painter's lover.",
      "extraLink": "https://www.theguardian.com/artanddesign/2019/nov/15/dora-maar-picassos-weeping-woman"
    },
    "1005_BoulevardMontmartre_CamillePissarro":{
      "art": "1005_BoulevardMontmartre_CamillePissarro",
      "title": "The Boulevard Montmartre on a Winter Morning",
      "artist": "Camille Pissarro",
      "nationality": "Danish-French",
      "pob": "Charlotte Amalie",
      "yob": 1830,
      "yod": 1903,
      "pod": "Paris",
      "paintingDate": "1897",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Gray and dreary the mornings be. I hope you are enjoying your pee.",
      "extraLink": "https://www.metmuseum.org/art/collection/search/437310"
    },
    "1101_ActualFractual_HowardArkley":{
      "art": "1101_ActualFractual_HowardArkley",
      "title": "Actual fractual",
      "artist": "Howard Arkley",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1951,
      "yod": 1999,
      "pod": "Melbourne",
      "paintingDate": "1994",
      "medium": "Synthetic polymer paint on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "What does 'fractual' mean? Your guess is as good as mine. Is it referencing fractals? Facts? I have no idea.",
      "extraLink": "https://www.ngv.vic.gov.au/school_resource/suburban-collages-inspired-by-howard-arkleys-actual-fractual/"
    },
    "1102_TheHuntersInTheSnow_PeterBruegel":{
      "art": "1102_TheHuntersInTheSnow_PeterBruegel",
      "title": "Hunters in the Snow (Winter)",
      "artist": "Pieter Bruegel the Elder",
      "nationality": "Dutch",
      "pob": "Breda or Breugel",
      "yob": "c. 1525-1530",
      "yod": 1569,
      "pod": "Brussels",
      "paintingDate": "1565",
      "medium": "Oil on wood",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Beautiful painting.",
      "extraLink": "https://smarthistory.org/pieter-bruegel-the-elder-hunters-in-the-snow-winter/"
    },
    "1103_TigerInATropicalStorm_HenriRousseau":{
      "art": "1103_TigerInATropicalStorm_HenriRousseau",
      "title": "",
      "artist": "Henri Rousseau",
      "nationality": "French",
      "pob": "Laval",
      "yob": 1844,
      "yod": 1910,
      "pod": "Paris",
      "paintingDate": "1891",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Whenever I am sad, I look at this tiger's face and the world seems that little bit better. Just look at that tiger's face. How could it not make you happy? An alternate title for this piece is <i>Surprised!</i>",
      "extraLink": "https://www.youtube.com/watch?v=JQYrBWnJW4s"
    },
    "1104_HaystackInTheMorning_ClaudeMonet":{
      "art": "1104_HaystackInTheMorning_ClaudeMonet",
      "title": "Haystack, Morning Snow Effect",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "1891",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Hey look, it's Monet. Let us flip a coin and see if it is going to be a haystack or a water lily. It is fascinating to see all the haystacks lined up next to each other and the differences between them (see the link). But get a different subject my guy.",
      "extraLink": "https://en.wikipedia.org/wiki/Haystacks_(Monet_series)"
    },
    "1105_BruteFolly_FranciscoGoyaYLucientes":{
      "art": "1105_BruteFolly_FranciscoGoyaYLucientes",
      "title": "Brute folly (Disparate de bestia)",
      "artist": "Francisco Goya",
      "nationality": "Spanish",
      "pob": "Fuendetodos",
      "yob": 1746,
      "yod": 1828,
      "pod": "Bordeaux",
      "paintingDate": "c.1816-1823",
      "medium": "Etching and aquatint in dark umber ink",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This elephant looks like it has walked up to you as you exit a night club, looking to bum some peanuts.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/26000/"
    },
    "1201_WaxDogsOnLakeEyre_LinOnus":{
      "art": "1201_WaxDogsOnLakeEyre_LinOnus",
      "title": "Wax Dogs on Lake Eyre",
      "artist": "Lin Onus",
      "nationality": "Australian",
      "pob": "Boroondara",
      "yob": 1948,
      "yod": 1996,
      "pod": "Naarm",
      "paintingDate": "unknown painting date",
      "medium": "Probably oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This one took forever to hunt down. You lot don't appreciate just how much effort goes into some of these. This digital image was buried in a pdf of a brochure I found online. However, I could not find the painting date.",
      "extraLink": "https://www.artgallery.nsw.gov.au/collection/artists/onus-lin/"
    },
    "1202_Summertime_MaryCassatt":{
      "art": "1202_Summertime_MaryCassatt",
      "title": "Summertime",
      "artist": "Mary Cassat",
      "nationality": "American",
      "pob": "Allegheny",
      "yob": 1844,
      "yod": 1926,
      "pod": "Château de Beaufresne",
      "paintingDate": "1894",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "You just know that at least one hat will be lost to those murky depths. This piece was influenced by Japanese art, much in the same way that <i>My Adventures with Superman</i> invokes anime tropes.",
      "extraLink": "https://conversations.terraamericanart.org/artworks/summertime/"
    },
    "1203_BalDuMoulinDeLaGalette_Pierre-AugusteRenoir":{
      "art": "1203_BalDuMoulinDeLaGalette_Pierre-AugusteRenoir",
      "title": "Bal du moulin de la Galette",
      "artist": "Pierre-Auguste Renoir",
      "nationality": "French",
      "pob": "Limoges",
      "yob": 1841,
      "yod": 1919,
      "pod": "Cagnes-sur-Mer",
      "paintingDate": "1876",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The painting depicts a typical Sunday afternoon at the original Moulin de la Galette in the district of Montmartre in Paris. In the late 19th century, working-class Parisians would dress up and spend time there dancing, drinking, and eating galettes into the evening. Which is a lovely way to spend a Sunday.",
      "extraLink": "https://en.wikipedia.org/wiki/Bal_du_moulin_de_la_Galette"
    },
    "1301_UntitledDog_KeithHarring":{
      "art": "1301_UntitledDog_KeithHarring",
      "title": "Untitled (Dog Dancing)",
      "artist": "Keith Harring",
      "nationality": "American",
      "pob": "Reading",
      "yob": 1958,
      "yod": 1990,
      "pod": "New York",
      "paintingDate": "1980s sometime",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "For some reason this artwork is all over the online auction houses. People cannot get enough of it I suppose. I also took the squiggles to spell 'Ini' but on further reflection they appear to be movement lines.",
      "extraLink": "https://www.ngv.vic.gov.au/school_resource/digital-creatives-keith-harings-digital-dance-club/"
    },
    "1302_IdeasOfBarak_VernonAhKee":{
      "art": "1302_IdeasOfBarak_VernonAhKee",
      "title": "Ideas of Barak",
      "artist": "Vernon Ah Kee",
      "nationality": "Australian",
      "pob": "Innisfail",
      "yob": 1967,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2011",
      "medium": "Black charcoal on primed acrylic",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "William Barak, the subject of this painting, was the last leader of the Yarra-Yarra tribe and an accomplished artist. He died in 1903 but his name is all over the place here in Victoria. There is the William Barak Bridge near the MCG, there is a giant image of him on the Barak building along Swanston Street. He was really the one who represented indigenous interests to the governing forces at the time.",
      "extraLink": "https://www.ngv.vic.gov.au/multimedia/vernon-ah-kee-investigating-ideas-of-barak/"
    },
    "1303_Number6_JacksonPollock":{
      "art": "1303_Number6_JacksonPollock",
      "title": "Number 6",
      "artist": "Jackson Pollock",
      "nationality": "American",
      "pob": "Cody",
      "yob": 1912,
      "yod": 1956,
      "pod": "Springs",
      "paintingDate": "1949",
      "medium": "Duco and aluminum paint on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Gesundheit.",
      "extraLink": "https://emuseum.mfah.org/objects/47833/number-6"
    },
    "1304_WhenWillYouMarry_PaulGauguin":{
      "art": "1304_WhenWillYouMarry_PaulGauguin",
      "title": "When Will You Marry?",
      "artist": "Paul Gaugin",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1848,
      "yod": 1903,
      "pod": "Atuona",
      "paintingDate": "1892",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "So, this artist travels to Tahiti with the sole purpose to find a paradise where he could create pure primitive art, unlike all the faux primitive art being created in France at the time. First off, rude. Secondly, he arrived and found Tahiti to be colonised and two thirds of the indigenous population had been killed by colonial disease. He did some paintings anyway. They were not well received back in France. Just recently this one sold for US$210 million.",
      "extraLink": "https://en.wikipedia.org/wiki/When_Will_You_Marry%3F"
    },
    "1305_TeaAndCoffeeSalon_SaboSaekiShunko":{
      "art": "1305_TeaAndCoffeeSalon_SabōSaekiShunko",
      "title": "Tea and coffee salon, Sabō",
      "artist": "Saeki Shunko",
      "nationality": "Japanese",
      "pob": "Toyama Prefecture",
      "yob": 1909,
      "yod": 1942,
      "pod": "",
      "paintingDate": "1939",
      "medium": "ink, colour, paper, lacquer",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I take my tea black but with two ice cubes. Tara has hers with a dash of milk and one sugar.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/117866/"
    },
    "1306_TheSonOfMan_ReneMagritte":{
      "art": "1306_TheSonOfMan_ReneMagritte",
      "title": "The Son of Man",
      "artist": "Rene Magritte",
      "nationality": "Belgian",
      "pob": "Lessines",
      "yob": 1898,
      "yod": 1967,
      "pod": "Rue des Mimosas",
      "paintingDate": "1964",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "You ever have one of those days where you just feel off. Perhaps your limbs are weak and you feel faint and dizzy? It might be because you have not eaten enough and your blood sugars are low. Eating an apple is a great way to rectify this situation. Apples. Yes Please.",
      "extraLink": "https://en.wikipedia.org/wiki/The_Son_of_Man"
    },
    "1307_IAmAMermaid_EuniceDjerrknuYunupinu":{
      "art": "1307_IAmAMermaid_EuniceDjerrkŋuYunupiŋu",
      "title": "I am a Mermaid",
      "artist": "Djerrkŋu Yunupiŋu (Eunice)",
      "nationality": "Australian",
      "pob": "Inglis Island",
      "yob": "c.1945",
      "yod": 2022,
      "pod": "Yirrkala",
      "paintingDate": 2020,
      "medium": "Earth pigments and recycled print toner on Stringybark (Eucalyptus sp.)",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is my favourite one.",
      "extraLink": "https://www.ngv.vic.gov.au/multimedia/djerrkngu-yunupingu-i-am-a-mermaid/"
    },
    "1401_ElephantWalking_EadweardMuybridge":{
      "art": "1401_ElephantWalking_EadweardMuybridge",
      "title": "Elephant Walking",
      "artist": "Eadweard Muybridge",
      "nationality": "English",
      "pob": "Kingston upon Thames",
      "yob": 1830,
      "yod": 1904,
      "pod": "Kingston upon Thames",
      "paintingDate": "1887",
      "medium": "Collotype",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Muybridge took it upon himself to document animal locomotion. He did 781 of these collotypes, a lot of them were horses, this one is an elephant.",
      "extraLink": "https://www.nga.gov/collection/art-object-page.136541.html"
    },
    "1402_MonaLisa_LeonardoDaVinci":{
      "art": "1402_MonaLisa_LeonardoDaVinci",
      "title": "Mona Lisa",
      "artist": "Leonardo da Vinci",
      "nationality": "Italian",
      "pob": "Anchiano",
      "yob": 1452,
      "yod": 1519,
      "pod": "Château du Clos Lucé",
      "paintingDate": "1503-1506",
      "medium": "Oil on poplar panel",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "It took Leo three years to paint this tiny painting. I'm not saying this painting is overblown but three years? I'm quite sure it didn't take three years to make this emoji: 😏, which is pretty much the same thing. The linked Wikipedia article goes into how it only got popular after someone stole it in 1911 which is worth a read.",
      "extraLink": "https://en.wikipedia.org/wiki/Mona_Lisa"
    },
    "1403_HousesAtAuvers_VincentVanGogh":{
      "art": "1403_HousesAtAuvers_VincentVanGogh",
      "title": "Houses in Auvers",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "1890",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Monet had their water lilies and haystacks, Van Gogh had these houses in Auvers. Dude was obsessed with them. Bit too smudged for my liking though, three stars.",
      "extraLink": "https://www.vincentvangogh.org/houses-in-auvers.jsp"
    },
    "1404_TheBanquetOfCleopatra_GiovanniBattistaTiepolo":{
      "art": "1404_TheBanquetOfCleopatra_GiovanniBattistaTiepolo",
      "title": "The Banquet of Cleopatra",
      "artist": "Giovanni Battista Tiepolo",
      "nationality": "Italian",
      "pob": "Venice",
      "yob": 1696,
      "yod": 1770,
      "pod": "Madrid",
      "paintingDate": "1743-1744",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is basically fan art of Cleopatra and Mark Antony. This one is great because of the dogs, cannot go wrong with adding some dogs in. In this painting, the mad lad Cleo is dissolving her pearl earring in a glass of vinegar to drink it, to 'own' Antony and win a bet to see who could make a more lavish banquet.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/4409/"
    },
    "1405_HorsesBathingInTheSea_LucyKemp":{
      "art": "1405_HorsesBathingInTheSea_LucyKemp",
      "title": "Horses Bathing in the Sea",
      "artist": "Lucy Kemp-Welch",
      "nationality": "British",
      "pob": "Bournemouth",
      "yob": 1869,
      "yod": 1958,
      "pod": "Watford",
      "paintingDate": "1899",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Horses in the sea, <br>getting clean at last.<br>Watch them leap with glee, <br>watch them take a bath.<br>And the men as well, getting cleaner too.<br>Just imagine the horse poo, ah-ah. <br>Just floating in the water, ah-ah.<br>",
      "extraLink": "https://www.ngv.vic.gov.au/essay/horses-bathing-in-the-sea-by-lucy-kemp-welch-1869-1958-the-paintings-genesis-2/"
    },
    "1501_ThePersistanceOfMemory_SalvadorDali":{
      "art": "1501_ThePersistanceOfMemory_SalvadorDali",
      "title": "The Persistence of Memory",
      "artist": "Salvador Dali",
      "nationality": "Spanish",
      "pob": "Figueres",
      "yob": 1904,
      "yod": 1989,
      "pod": "Figueres",
      "paintingDate": "1931",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Comedian: Man, it is hot today.<br>Audience: How hot is it?<br>Comedian: <b><i>The Persistence of Memory</b></i>, 1931, by <b>Salvador Dali</b> (Spanish, 1904-1989)<br>Audience (later): How did they do that with their voice?<br>",
      "extraLink": "https://www.moma.org/collection/works/79018"
    },
    "1502_DancersInBlue_EdgarDagas":{
      "art": "1502_DancersInBlue_EdgarDagas",
      "title": "Dancers in Blue",
      "artist": "Edgar Degas",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1834,
      "yod": 1917,
      "pod": "Paris",
      "paintingDate": "1890",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Dude loved the ballet, at least he loved painting ballerinas. We went to the Alice in Wonderland ballet; it had two intermissions. They had small children dressed up as hedgehogs do forward rolls and everyone liked that.",
      "extraLink": "https://www.thehistoryofart.org/edgar-degas/blue-dancers/"
    },
    "1503_MorningSunlightOnTheSnow_CamillePissarro":{
      "art": "1503_MorningSunlightOnTheSnow_CamillePissarro",
      "title": "Morning Sunlight on the Snow",
      "artist": "Camille Pissarro",
      "nationality": "Danish-French",
      "pob": "Charlotte Amalie",
      "yob": 1830,
      "yod": 1903,
      "pod": "Paris",
      "paintingDate": "1895",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Looks brisk. You must wonder if the artist was on site to paint this one. I sure hope they were rugged up otherwise it would have been a <i>pain</i>ting to make!<br>If you liked that joke I regularly perform with <i>The Big Hoo-Haa! Melbourne</i> most Saturdays.",
      "extraLink": "https://collections.mfa.org/objects/31810"
    },
    "1504_FlyingCloud_KennethMacqueen":{
      "art": "1504_FlyingCloud_KennethMacqueen",
      "title": "(Flying Cloud)",
      "artist": "Kenneth McQueen",
      "nationality": "Australian",
      "pob": "",
      "yob": 1897,
      "yod": 1960,
      "pod": "",
      "paintingDate": "c.1950",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "They say good art asks questions. It is my thesis that this artist realised their painting was not asking any hard-hitting questions besides from, 'Why the cloud be like that?' so they threw the title in parenthesis just to have something to make the audience ponder. What could the parenthesis mean?<br>It is a nice cloud though. ",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/flying-cloud/"
    },
    "1505_TheWaterLilyPond_ClaudeMonet":{
      "art": "1505_TheWaterLilyPond_ClaudeMonet",
      "title": "The Water-Lily Pond",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "1899",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Well what a surprise. Monet is back with some more water lilies, who would have thought? Fair play though, if I saw that scenery I would have taken a photo, Monet was just working with the tools at his disposal.",
      "extraLink": "https://www.nationalgallery.org.uk/paintings/claude-monet-the-water-lily-pond"
    },
    "1506_ItsOurDestiny2_EkoNugroho":{
      "art": "1506_It'sOurDestiny2_EkoNugroho",
      "title": "It's our destiny 2",
      "artist": "Eko Nugroho",
      "nationality": "Indonesian",
      "pob": "Yogyakarta",
      "yob": 1977,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2012",
      "medium": "Synthetic polymer paint and fibre-tipped pen on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Selamat pagi, some Indonesian representation! I would say this piece is baik. Even going as far to say it is baik sekali. God, I hope my high school Indonesian is correct.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/114978/"
    },
    "1507_AbstractPainting_GerhardRichter":{
      "art": "1507_AbstractPainting_GerhardRichter",
      "title": "Abstract Painting (725-3)",
      "artist": "Gerhard Richter",
      "nationality": "German",
      "pob": "Dresden",
      "yob": 1932,
      "yod": "Present",
      "pod": "",
      "paintingDate": "1990",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is another artist that needs a better naming convention. At least in this one he includes numbers in the title to differentiate. This painting is how I feel when I am recovering from a cold. What about you?",
      "extraLink": "https://www.ngv.vic.gov.au/gerhard-richter-abstract-painting-725-3-1990/"
    },
    "1601_HamLongStreet_BuiXuanPhai":{
      "art": "1601_HamLongStreet_BuiXuanPhai",
      "title": "Ham Long Street",
      "artist": "Bùi Xuân Phái",
      "nationality": "Vietnamese",
      "pob": "Hanoi",
      "yob": 1920,
      "yod": 1988,
      "pod": "Hanoi",
      "paintingDate": "c.1984",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is another tricky one with hardly anything to find on the internet on this specific piece. The artist is well known for painting the old quarter in Hanoi.  It's a beautiful place, and we would recommend you go if you ever find yourself in Vietnam. Jonah made a friend, Bobby, when we were staying there. And that is when he also took up the hobby of picking up stools and moving them round the shops, much like a miniature poltergeist would.",
      "extraLink": "https://www.hanoiarttours.com/bui-xuan-phai-painter/"
    },
    "1602_Self-Portrait_VincentVanGogh":{
      "art": "1602_Self-Portrait_VincentVanGogh",
      "title": "Self-Portrait",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "1889",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Is he a friend or a foe? It's your boy Van Gogh.<br>You better not cough, it's your boy Van Gogh.<br>He'll eat you out like a hog, it's your boy Van Gogh.<br>",
      "extraLink": "https://artsandculture.google.com/asset/self-portrait/9gFw_1Vou2CkwQ?hl=en"
    },
    "1603_DrySalvages_JohnOlsen":{
      "art": "1603_DrySalvages_JohnOlsen",
      "title": "Dry Salvages",
      "artist": "John Olsen",
      "nationality": "Australian",
      "pob": "Newcastle",
      "yob": 1928,
      "yod": 2023,
      "pod": "Bowrai",
      "paintingDate": "1956",
      "medium": "Oil on hardboard",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Dry Salvages takes its namesake from the T.S. Eliot poem which makes this either homage, inspiration, plagiarism. Please vote by doing a pee for homage, a poo for inspiration, and a Number 3 for plagiarism.",
      "extraLink": "https://www.artgallery.nsw.gov.au/collection/works/68.1972/#about"
    },
    "1604_TheLacquerRoom_GraceCossingtonSmith":{
      "art": "1604_TheLacquerRoom_GraceCossingtonSmith",
      "title": "The Lacquer Room",
      "artist": "Grace Cossington Smith",
      "nationality": "Australian",
      "pob": "Neutral Bay",
      "yob": 1892,
      "yod": 1984,
      "pod": "Roseville",
      "paintingDate": "1936",
      "medium": "Oil on paperboard on plywood",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I love the little man staring directly at the audience in this painting. His blue eyes pierce right out of the painting. What is your story strange man sitting in a David Jones cafeteria? We will never know.",
      "extraLink": "https://www.artgallery.nsw.gov.au/collection/works/OA10.1967/#about"
    },
    "1605_JetStream_JulianOpie":{
      "art": "1605_JetStream_JulianOpie",
      "title": "Jet Stream",
      "artist": "Julian Opie",
      "nationality": "British",
      "pob": "London",
      "yob": 1958,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2011",
      "medium": "Continuous computer animation on LED screen, sound",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Julian Opie had this amazing exhibit at the NGV International a few years ago. He is a very fun artist. A lot of rotoscoped work. The birds out the front of the NGV International are Opie's as well. The original work had an audio landscape which unfortunately does not translate to a lenticular postcard. Click the link to see it in motion.",
      "extraLink": "https://www.julianopie.com/film/2011/jet-stream"
    },
    "1606_MeadowWithPoplars_ClaudeMonet":{
      "art": "1606_MeadowWithPoplars_ClaudeMonet",
      "title": "Meadow with Poplars",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "1875",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "People have accused me of being negative about Monet, that he only paints water-lilies or haystacks, so far play to the man, this painting is neither of those things (even if I can see some haystacks in the distance). It is a beautiful painting and makes me nostalgic for a time I did not inhabit. I can feel the warmth of the sun on my face and carefree innocence in the air.",
      "extraLink": "https://commons.wikimedia.org/wiki/File:Monet_Meadow-with-Poplars-Homepage.jpg"
    },
    "1701_MondayMorning_VidaLahey":{
      "art": "1701_MondayMorning_VidaLahey",
      "title": "Monday morning",
      "artist": "Vida Lahey",
      "nationality": "Australian",
      "pob": "Pimpama",
      "yob": 1882,
      "yod": 1968,
      "pod": "Wonga",
      "paintingDate": "1912",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Mondays am I right?",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/monday-morning/"
    },
    "1702_WomanInAnArmchair_PabloPicasso":{
      "art": "1702_WomanInAnArmchair_PabloPicasso",
      "title": "Woman in an armchair (Femme dans un fauteuil)",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "1927",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I can see the woman. And I can kind of see the armchair but only because the title of the piece told me to look for an armchair. Without knowledge of the title I would have interpreted it as a woman stealing a framed piece of art at sunset. What about you? Please write your response on one (1) square of toilet paper using a writing implement of your choice.",
      "extraLink": "https://artguide.com.au/an-embracing-tussle-five-contemporary-artists-on-picasso/"
    },
    "1703_ASceneOnTheIceNearATown_HendrickAvercamp":{
      "art": "1703_ASceneOnTheIceNearATown_HendrickAvercamp",
      "title": "A Scene on the Ice near a Town",
      "artist": "Hendrick Avercamp",
      "nationality": "Dutch",
      "pob": "Amsterdam",
      "yob": 1585,
      "yod": 1634,
      "pod": "Kampen",
      "paintingDate": "c.1615",
      "medium": "Oil on oak",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Did you know there was a little ice age that hit northern Europe in the 17th Century? Well now you do. This piece gives me <i>Where's Wally?</i> in the nicest way possible. This one is dense!",
      "extraLink": "https://www.nationalgallery.org.uk/paintings/hendrick-avercamp-a-scene-on-the-ice-near-a-town"
    },
    "1704_ApplesAndOranges_PaulCezanne":{
      "art": "1704_ApplesAndOranges_PaulCézanne",
      "title": "Still Life with Apples and Oranges",
      "artist": "Paul Cézanne",
      "nationality": "French",
      "pob": "Aix-en-Provence",
      "yob": 1839,
      "yod": 1906,
      "pod": "Aix-en-Provence",
      "paintingDate": 1895,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "There's a pitcher in the picture!",
      "extraLink": "https://www.paulcezanne.org/still-life-with-apples-and-oranges.jsp"
    },
    "1801_AgainstAllOdds_BrookAndrew":{
      "art": "1801_AgainstAllOdds_BrookAndrew",
      "title": "Against all odds",
      "artist": "Brook Andrew",
      "nationality": "Australian",
      "pob": "Sydney",
      "yob": 1970,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2005",
      "medium": "Collage of cut colour screenprint on screenprint",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Against all odds, attached to nothing surprising, the uprising. Brook Andrew is a first nation's man. I have seen this piece in pink as well, which suggests there are more copies out there coloured differently.",
      "extraLink": "https://www.geelonggallery.org.au/whats-on/exhibitions/brook-andrew-hope-peace-and-paradise/hope-and-peace-series"
    },
    "1802_HorsemanInLandscape_FredWilliams":{
      "art": "1802_HorsemanInLandscape_FredWilliams",
      "title": "Horseman in landscape",
      "artist": "Fred Williams",
      "nationality": "Australian",
      "pob": "Richmond",
      "yob": 1927,
      "yod": 1982,
      "pod": "Hawthorn",
      "paintingDate": "1968",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I am a big fan of the Australiana landscape. Or rather, I am a big fan of the idea of the Australiana landscape. This just speaks to me even though I cannot see any horseman. Maybe they are shy.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/3214/"
    },
    "1803_MortaruruWithRedOverhead_AleksandrVolkov":{
      "art": "1803_MortaruruWithRedOverhead_AleksandrVolkov",
      "title": "Mortaruru with Red Overhead",
      "artist": "Willi Baumeister",
      "nationality": "German",
      "pob": "",
      "yob": 1889,
      "yod": 1955,
      "pod": "",
      "paintingDate": "1953",
      "medium": "Not sure, probably oil on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "It's giving angry snowman.",
      "extraLink": "https://www.etsy.com/listing/1661218869/willi-baumeister-mortaruru-with-red?gpla=1&gao=1&"
    },
    "1804_ALionAttackingAHorse_GeorgeStubbs":{
      "art": "1804_ALionAttackingAHorse_GeorgeStubbs",
      "title": "A Lion Attacking a Horse",
      "artist": "George Stubbs",
      "nationality": "English",
      "pob": "Liverpool",
      "yob": 1724,
      "yod": 1806,
      "pod": "Marylebone",
      "paintingDate": "1762",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Interestingly, in trying to find this piece I came across very similar pieces. The lion and horse would be in the same pose but their colour would be different or transposed to a different environment. So, he got very good at drawing lions attacking horses by the end. He could probably do it in his sleep <i>lying</i> down.",
      "extraLink": "https://www.ngv.vic.gov.au/explore/collection/work/4393/"
    },
    "1805_ManInBlue_PabloPicasso":{
      "art": "1805_ManInBlue_PabloPicasso",
      "title": "Man in Blue",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "c.1902",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is from Picasso's 'Blue Period', which has its own Wikipedia entry. It comprised of a lot of blue paintings and a lot of sad subjects. This is one of them.",
      "extraLink": "https://www.wikiart.org/en/pablo-picasso/man-in-blue"
    },
    "1806_SpringScene_RupertBunny":{
      "art": "1806_SpringScene_RupertBunny",
      "title": "Spring scene",
      "artist": "Rupert Bunny",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1864,
      "yod": 1947,
      "pod": "Melbourne",
      "paintingDate": "c.1921",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is one of my favourites. Jonah is adamant this one is a painting of Tara. Which one do you think Jonah thinks is of me? Here is a hint, it is not flattering.",
      "extraLink": "https://www.tumblr.com/thewondermentofillustration/667293137755062272/rupert-bunny-spring-scene-circa-1921-oil-on"
    }
  }
