// $( document ).ready(function(){
//     // without animation
//     /*
//     $("#close-btn").click(function(){
//        $(".small-image").removeClass('active');
//       $("#show_image_popup").hide();
//     })
  
  
//     $(".small-image").click(function(){
//        // add active class
//        $(this).addClass('active');
//       var image_path = $(this).attr('src'); 
//       $("#show_image_popup").hide();
//       // now st this path to our popup image src
//       $("#show_image_popup").show();
//       $("#large-image").attr('src',image_path);
  
//     })
//   */
  
//     // with animation  
  
//       $("#close-btn").click(function(){
//          // remove active class from all images
//         $(".small-image").removeClass('active');
//         $("#show_image_popup").slideUp();
//       })
  
//       $(".small-image").click(function(){
//           // remove active class from all images
//          $(".small-image").removeClass('active');
//         // add active class
//          $(this).addClass('active');
  
//         var image_path = $(this).attr('src'); 
//         $("#show_image_popup").fadeOut();
//         // now st this path to our popup image src
//         $("#show_image_popup").fadeIn();
//         $("#large-image").attr('src',image_path);
  
//       })
  
//   })

  var small_images  = document.getElementsByClassName("small-image");
  var show_image_popup  = document.getElementById("show_image_popup");
  var large_image  = document.getElementById("large-image");
  var close_btn = document.getElementById("close-btn");
  
  window.addEventListener("load",function(){
  var svgObject = document.getElementById('svg_file').contentDocument;
  var svg = svgObject.getElementsByClassName("small-image")
  });
  
function display_popup_from_svg(id_of_painting){
  var filepath='images/individual_art/'+id_of_painting+'.jpg'
  large_image.src=filepath
  var artistString = '<em>'+artData[id_of_painting]["artist"]+'</em>'+' ('+artData[id_of_painting]['nationality']+', '+artData[id_of_painting]['yob']+'-'+artData[id_of_painting]['yod']+')';
  var titleString = '<i><b>'+artData[id_of_painting]['title']+',</i></b>'+' '+artData[id_of_painting]['paintingDate'];
  var mediumString = artData[id_of_painting]['medium'];
  var extraLinkString = 'For more information please visit <a href='+artData[id_of_painting]["extraLink"]+'> this site</a>.';
  
  document.getElementById("title").innerHTML = titleString;
  document.getElementById("artist").innerHTML = artistString;
  document.getElementById('medium').innerHTML = mediumString;
  document.getElementById('comment').innerHTML = artData[id_of_painting]['comment']
  document.getElementById('extraLink').innerHTML = extraLinkString
  showModal();
}
  
  function showModal(){
    show_image_popup.style.display = 'block';
  }
  
  close_btn.addEventListener("click", function(){
    // before colose the modal we need to remove active class
    for(var i=0; i< small_images.length; i++){
      small_images[i].classList.remove('active');
    }
    // end
    closeModal();
  });
  
  function closeModal(){
    show_image_popup.style.display = 'none';
  }


  //writing in all the artData, there must be a cleaner way to do this. JS is so janky

  let artData = {
    "0101_Pity_WilliamBlake":{
      "art": "0101_Pity_WilliamBlake",
      "title": "Pity",
      "artist": "William Blake",
      "nationality": "English",
      "pob": "Soho",
      "yob": 1757,
      "yod": 1827,
      "pod": "London",
      "paintingDate": "c. 1795",
      "medium": "Colour print, finished in ink and watercolour, on paper",
      "style": "Romanticism?",
      "genre": "",
      "period": "",
      "comment": "This artwork is a literal illustration of a double simile from <i>Macbeth</i>, found in the lines: <blockquote>And pity, like a naked new-born babe,\nStriding the blast, or heaven's cherubim, hors'd\nUpon the sightless couriers of the air.\n- Macbeth (1.7.21–23)[3]</blockquote>",
      "extraLink": "https://www.metmuseum.org/art/collection/search/347416"
    },
    '0102_TheBattleOfSanRomano_PaoloUccello':{
      "art": "0102_TheBattleOfSanRomano_PaoloUccello",
      "title": "The Battle of San Romano",
      "artist": "Paolo Uccello",
      "nationality": "Italian",
      "pob": "Pratovecchio",
      "yob": 1397,
      "yod": 1475,
      "pod": "Florence",
      "paintingDate": "c. 1438-1440",
      "medium": "Egg tempera with walnut oil and linssed oil on poplar",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The Battle of San Romano is a set of three paintings by the Florentine painter Paolo Uccello depicting events that took place at the Battle of San Romano between Florentine and Sienese forces in 1432. They are significant as revealing the development of linear perspective in early Italian Renaissance painting, and are unusual as a major secular commission. The paintings are in egg tempera on wooden panels, each over 3 metres long. According to the National Gallery,[1] the panels were commissioned by a member of the Bartolini Salimbeni family in Florence sometime between 1435 and 1460. The paintings were much admired in the 15th century; Lorenzo de' Medici so coveted them that he purchased one and had the remaining two forcibly removed to the Palazzo Medici. They are now divided between three collections, the National Gallery, London, the Galleria degli Uffizi, Florence, and the Musée du Louvre, Paris.",
      "extraLink": "https://www.beyondtheyalladog.com/2013/08/the-battle-of-san-romano-in-separate-pieces/"
    },
    '0103_TwoWomen_MaryCockburnMercer':{
      "art": "0103_TwoWomen_MaryCockburnMercer",
      "title": "(Two women)",
      "artist": "Mary Cockburn Mercer",
      "nationality": "Australian",
      "pob": "Scotland",
      "yob": 1882,
      "yod": 1963,
      "pod": "Aubagne",
      "paintingDate": "c. 1940",
      "medium": "Watercolour over pencil on buff paper",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Mary Cockburn Mercer, was an Australian painter. She spent the 1920s and 1930s in Europe, and the 1940s in Melbourne, Australia. Her final years were spent in France. She exhibited with the Contemporary Art Society in Australia. This painting is of two close friends hanging out.",
      "extraLink": "https://www.ngv.vic.gov.au/custom/screens/josephbrown/index.php?artistid=14217&chapter=3"
    },
    '0201_MotherAndChild1907_PabloPicasso':{
      "art": "0201_MotherAndChild1907_PabloPicasso",
      "title": "Mother and child",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": 1907,
      "medium": "Oil on canvas",
      "style": "Cubism",
      "genre": "",
      "period": "",
      "comment": "This is classic Picasso. See how the faces don't look like faces but they feel like faces? Classic Picasso. This is one of many paintings by Picasso depicting a mother and child. So I don't know if he had a weird Freud thing going on, or just lived the subject matter. It also made hunting down this particular mother and child quite difficult. So, you're welcome.",
      "extraLink": "https://arthive.com/pablopicasso/works/376118~Mother_and_child"
    },
    "0202_IfNotNo_RonaldBrooksKitaj":{
      "art": "0202_IfNotNo_RonaldBrooksKitaj",
      "title": "If Not, Not",
      "artist": "Robert Brooks Kitaj",
      "nationality": "American",
      "pob": "Chagrin Falls",
      "yob": 1932,
      "yod": 2007,
      "pod": "Los Angeles",
      "paintingDate": "1975-1976",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Believe it or not, this is a self portrait. The artist is the one holding the baby in bed. This piece also makes many references to TS Elliot's poem The Waste Land. I think it's about the holocaust? The artist is Jewish and has a few pieces exploring that subject. Also great name for a painting.",
      "extraLink": "https://www.nationalgalleries.org/art-and-artists/644/if-not-not"
    },
    "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid":{
      "art": "0203_QFromTheRainbowAphorismsSeries_DavidMcDiarmid",
      "title": "Q",
      "artist": "David McDiarmid",
      "nationality": "Australian",
      "pob": "Hobart",
      "yob": 1952,
      "yod": 1995,
      "pod": "Sydney",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "So this one is a bit hard to pin down. There was a Rainbow Aphorism series and this one is one of them. David MacDiarmid was an artist, designer and political activist, recognised for his prominent and sustained artistic engagement in issues relating to gay male identity and HIV/AIDS. He is also known for his involvement in the gay liberation movement of the early 1970s, when he was the first person arrested at a gay rights protest in Australia, as well as his artistic direction of the Sydney Gay and Lesbian Mardi Gras. From its inception, McDiarmid's art career encompassed, as both subject and inspiration, gay male sexuality, politics and urban subcultures.",
      "extraLink": "https://fabricquarterly.com.au/2020/10/i-want-a-future-that-lives-up-to-my-past-david-mcdiarmid-and-local-queer-stories/"
    },
    "0204_GreatStillLifeOnPedestal_PabloPicasso":{
      "art": "0204_GreatStillLifeOnPedestal_PabloPicasso",
      "title": "Still Life on a Pedestal Table",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": 1931,
      "medium": "Oil on canvas",
      "style": "Surrealism",
      "genre": "Still life",
      "period": "Neoclassicist & Surrealist Period",
      "comment": "Another Picasso but this one is surreal instead of a bunch of cubes. I sort of see a dog in there if I squint 🤷. What do you see? When you come out of the toilet mention it to us!",
      "extraLink": "https://arthive.com/pablopicasso/works/619569~Still_Life_on_a_Pedestal_Table"
    },
    "0205_RembrandtSelf-PortraitWithTwoCircles_Rembrandt":{
      "art": "0205_RembrandtSelf-PortraitWithTwoCircles_Rembrandt",
      "title": "Self Portrait with Two Circles",
      "artist": "Rembrandt Harmenszoon van Rijn",
      "nationality": "Dutch",
      "pob": "Leiden",
      "yob": 1606,
      "yod": 1669,
      "pod": "Amsterdam",
      "paintingDate": 1665,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at this absolute beast of a painter smashing together this self portrait. The self assured grin. He knows he's considered a master in his art. And then just to flex he throws in two perfectly drawn circles. Because why not?",
      "extraLink": "https://www.rembrandtpaintings.com/self-portrait-with-two-circle.jsp"
    },
    "0206_PankASquith":{
      "art": "0206_PankASquith",
      "title": "Pank-a-Squith",
      "artist": "British Women's Social and Political Union",
      "nationality": "-",
      "pob": "-",
      "yob": "-",
      "yod": "-",
      "pod": "-",
      "paintingDate": "c. 1909",
      "medium": "Ink on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Roll on up and roll the dice because this one is a board game! Pank-a-Squith was a political board game about the suffragette movement created around 1909. It was created for the British Women's Social and Political Union as a way to generate funds and help spread women's suffrage ideologies. You roll the dice to move the women closer to Parliament house.",
      "extraLink": "https://boardgamegeek.com/boardgame/14249/pank-squith"
    },
    "0207_LamentationTheMourningOfChrist_Giotto":{
      "art": "0207_LamentationTheMourningOfChrist_Giotto",
      "title": "Lamentation (The Mourning of Christ)",
      "artist": "Giotto di Bondone",
      "nationality": "Italian",
      "pob": "Florence",
      "yob": 1267,
      "yod": 1337,
      "pod": "Florence",
      "paintingDate": "c. 1304-1306",
      "medium": "Fresco",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Lamentation (The Mourning of Christ) is a fresco painted c.1305 by the Italian artist Giotto as part of his cycle of the Life of Christ on the interior walls of the Scrovegni Chapel in Padua, Italy. In the painting, the body of the crucified Christ has been lowered from the cross and laid on the ground, surrounded by his grieving mother and disciples. His head is held by Mary, his mother, and his feet by Mary Magdelene. John the Apostle throws his arms wide in despair. To the right, Nicodemus and Joseph of Arimathea wait to prepare the body to be laid in a tomb.",
      "extraLink": "https://www.thehistoryofart.org/giotto/lamentation/"
    },
    "0301_Primavera_SandroBotticelli":{
      "art": "0301_Primavera_SandroBotticelli",
      "title": "Primavera",
      "artist": "Sandro Botticelli",
      "nationality": "Italian",
      "pob": "Florence",
      "yob": 1445,
      "yod": 1510,
      "pod": "Florence",
      "paintingDate": "",
      "medium": "Tempera on large panel",
      "style": "Renaissance/Mythological Scene",
      "genre": "",
      "period": "",
      "comment": "You better believe this painting is depicting the Realm of Venus. Zephyr chases the nymph Chloris, who turns into the goddess Flora on the right. Venus is underneath a blindfolded cupid in flight with the three Graces and Mercury on the left.",
      "extraLink": "https://news.artnet.com/art-world/sandro-botticelli-primavera-4-things-to-know-1937013"
    },
    "0302_LittleThuy":{
      "art": "0302_LittleThuy",
      "title": "Little Thuy",
      "artist": "Trần Văn Cẩn",
      "nationality": "Vietnamese",
      "pob": "Kiến An",
      "yob": 1910,
      "yod": 1994,
      "pod": "Hanoi",
      "paintingDate": 1943,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "The character in the picture is Minh Thuy, the niece of the painter. it was painted in 1943, a few years before the August revolution against the French and Japanese colonial rule. Thuy is still alive (as of 2022), living with her children and grandchildren.",
      "extraLink": "https://e.vnexpress.net/news/culture/restoring-national-painting-treasure-little-thuy-a-labor-of-love-4490256.html"
    },
    "0303_TheScream_EdvardMunch":{
      "art": "0303_TheScream_EdvardMunch",
      "title": "The Scream",
      "artist": "Edvard Munch",
      "nationality": "Norwegian",
      "pob": "Adalsbruk",
      "yob": 1863,
      "yod": 1944,
      "pod": "Oslo",
      "paintingDate": 1893,
      "medium": "Oil, tempera, and pastel on cardboard",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "What a piece. The artist describes the inspiration for this image thusly: \"I was walking along the road with two friends – the sun was setting – suddenly the sky turned blood red – I paused, feeling exhausted, and leaned on the fence – there was blood and tongues of fire above the blue-black fjord and the city – my friends walked on, and I stood there trembling with anxiety – and I sensed an infinite scream passing through nature.\" 😱😱😱",
      "extraLink": "https://www.edvardmunch.org/the-scream.jsp"
    },
    "0304_TheRhinoceros_Albrecht":{
      "art": "0304_TheRhinoceros_Albrecht",
      "title": "The Rhinocerus",
      "artist": "Albrecht Dürer",
      "nationality": "German",
      "pob": "Nuremberg",
      "yob": 1471,
      "yod": 1528,
      "pod": "Nuremberg",
      "paintingDate": 1515,
      "medium": "Woodcut",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a woodcut of a rhinocerus that the artist never saw. Instead, this woodcut is based on an anonymous written description and brief sketch of an Indian rhinocerus brought to Lisbon in 1515. The rhinocerus in question subsequently died at sea when the King sent it to the pope as a gift. There is a german inscription on the woodcut that reads: \"On the first of May in the year 1513 AD [sic], the powerful King of Portugal, Manuel of Lisbon, brought such a living animal from India, called the rhinoceros. This is an accurate representation. It is the colour of a speckled tortoise,[1][d] and is almost entirely covered with thick scales. It is the size of an elephant but has shorter legs and is almost invulnerable. It has a strong pointed horn on the tip of its nose, which it sharpens on stones. It is the mortal enemy of the elephant. The elephant is afraid of the rhinoceros, for, when they meet, the rhinoceros charges with its head between its front legs and rips open the elephant's stomach, against which the elephant is unable to defend itself. The rhinoceros is so well-armed that the elephant cannot harm it. It is said that the rhinoceros is fast, impetuous and cunning",
      "extraLink": "https://www.rct.uk/collection/800198/a-rhinoceros"
    },
    "0305_ThePreciousBook_GwenJohn":{
      "art": "0305_ThePreciousBook_GwenJohn",
      "title": "The Precious Book",
      "artist": "Gwen John",
      "nationality": "Welsh",
      "pob": "Haverfordwest",
      "yob": 1876,
      "yod": 1939,
      "pod": "Dieppe",
      "paintingDate": "c. 1916-1926",
      "medium": "Oil on cavas laid on panel",
      "style": "Post-Impressionisim",
      "genre": "",
      "period": "",
      "comment": "I couldn't find much information on this piece, only that it is now in the public domain. She's holding the book with a handkerchief, I suppose that makes the book precious.",
      "extraLink": "https://www.wikiart.org/en/gwen-john/the-precious-book"
    },
    "0306_WomenAndBirdInTheMoonlight_JoanMiro":{
      "art": "0306_WomenAndBirdInTheMoonlight_JoanMiro",
      "title": "Women and Bird in the Moonlight",
      "artist": "Joan Miró",
      "nationality": "Spanish",
      "pob": "Barcelona",
      "yob": 1893,
      "yod": 1983,
      "pod": "Palma",
      "paintingDate": 1949,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "How does this speak to you? What does it say? A seemingly bundle of shapes at first - but there is a moon. There are human shapes. The colours are nice.",
      "extraLink": "https://www.tate.org.uk/art/artworks/miro-women-and-bird-in-the-moonlight-n06007"
    },
    "0307_DanteRunningFromTheThreeBeasts_WilliamBlake":{
      "art": "0307_DanteRunningFromTheThreeBeasts_WilliamBlake",
      "title": "Dante running from the Three Beasts",
      "artist": "William Blake",
      "nationality": "English",
      "pob": "Soho",
      "yob": 1757,
      "yod": 1827,
      "pod": "London",
      "paintingDate": "1824-1827",
      "medium": "Pen and ink and watercolour over pencil and black chalk",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Three beasts walk into a bar and Dante runs away. This is Blake illustrating the Divine Comedy (the one with the circles of hell). So, technically a very early version of fan art. Dante looks like he is in Warrior 2.",
      "extraLink": "https://artsandculture.google.com/asset/dante-running-from-the-three-beasts-william-blake/-wEF4rg1T7H2JA?hl=en"
    },
    "0401_TheGreatWave_KatsushikaHokusai":{
      "art": "0401_TheGreatWave_KatsushikaHokusai",
      "title": "The Great Wave off Kanagawa",
      "artist": "Katasushika Hokusai",
      "nationality": "Japanese",
      "pob": "Edo",
      "yob": 1760,
      "yod": 1849,
      "pod": "Tokyo",
      "paintingDate": 1831,
      "medium": "Ukiyo-e (Woodblock print)",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I got a coffee mug with this image on it. It's a beautiful piece and has been parodied and been an influence for many works throughout the ages. This is a part of a series of other artworks depicting Fuji-Yama and sure enough, Fuji-Yama is at the back, capped in snow. As Japanese read right to left one can argue that the proper way to view this image is to invert it. Doing so makes the wave feel more dangerous, as if it will crush the boat.",
      "extraLink": "https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa"
    },
    "0501_Ophelia_JohnEverettMillais":{
      "art": "0501_Ophelia_JohnEverettMillais",
      "title": "Ophelia",
      "artist": "John Everett Millais",
      "nationality": "English",
      "pob": "Southampton",
      "yob": 1829,
      "yod": 1896,
      "pod": "Kensington",
      "paintingDate": "1851-1852",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Imagine being Ophelia, fully clothed and just absolutely drenched in water. You better have hoped it was a hot day because my word I would be misrable if it was anything less than 40 degrees. It's a painting depicting <i>Hamlet</i>, Act IV, Scene vii where she oh..... she falls into a stream a drowns.",
      "extraLink": "https://www.tate.org.uk/art/artworks/millais-ophelia-n01506"
    },
    "0502_Self-PortraitAsTheAllegoryOfPainting_ArtemisiaGentileschi":{
      "art": "0502_Self-PortraitAsTheAllegoryOfPainting_ArtemisiaGentileschi",
      "title": "Self-Portrait as the Allegory of Painting (La Pittura)",
      "artist": "Artemisia Gentileschi",
      "nationality": "Italian",
      "pob": "Rome",
      "yob": 1593,
      "yod": 1653,
      "pod": "Naples",
      "paintingDate": "1638-1639",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a classic self-portrait of an artist. Bonus points for the artist painting another painting in the painting. In fact she is depicting herself as the female personification of Painting, But in a tongue in cheek way I think?",
      "extraLink": "https://www.rct.uk/collection/405551/self-portrait-as-the-allegory-of-painting-la-pittura"
    },
    "0503_Self-PortraitWithThornNecklaceAndHummingbird_FridaKahlo":{
      "art": "0503_Self-PortraitWithThornNecklaceAndHummingbird_FridaKahlo",
      "title": "Self-Portrait with Thorn Necklace and Hummingbird",
      "artist": "Frida Kahlo",
      "nationality": "Mexican",
      "pob": "Coyoacán",
      "yob": 1907,
      "yod": 1954,
      "pod": "Coyoacán",
      "paintingDate": 1940,
      "medium": "Oil on canvas on masonite",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "It's Kahlo! There's some animals here as well all with their own symbolism associated with them. The hummingbird could symbolise freedom but now it is dead, or it could represent a good luck charm for falling in love or it is meant to invoke the Aztec god of war. The monkey is a symbol of evil, but also she was gifted a spider monkey from Rivera whom she had just divorced. The thorns, is it meant to be christ like or just ouchy ouchy? Don't think about these things too hard. Just look at the pretty animals.",
      "extraLink": "https://www.fridakahlo.org/self-portrait-with-thorn-necklace-and-hummingbird.jsp"
    },
    "0504_LeGrandCanal_ClaudeMonet":{
      "art": "0504_LeGrandCanal_ClaudeMonet",
      "title": "Le Grand Canal",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": 1908,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "<i>Le Grand Canal</i> (or <i>The Grand Canal</i> in english) is one of six paintings looking down the canal towards the Salute Church. It's sort of like Magic: The Gathering where you have alternative art of the same card.it sold for $35 million in 2015. Here you can see it in the Toilet Gallery completely free of charge.",
      "extraLink": "https://en.wikipedia.org/wiki/Le_Grand_Canal"
    },
    "0505_TheKiss_GustavKlimt":{
      "art": "0505_TheKiss_GustavKlimt",
      "title": "The Kiss",
      "artist": "Gustav Klimt",
      "nationality": "Austrian",
      "pob": "Baumgarten",
      "yob": 1862,
      "yod": 1918,
      "pod": "Vienna",
      "paintingDate": "1907-1908",
      "medium": "Oil and gold leaf on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a classic piece. It was hailed as pornographic at the time of its unveiling. Actual gold leaf was used in it as well. Not in this postcard though, so please don't steal it.",
      "extraLink": "https://www.gustav-klimt.com/The-Kiss.jsp"
    },
    "0506_ArnolfiniPortrait_VanEyck":{
      "art": "0506_ArnolfiniPortrait_VanEyck",
      "title": "Arnolfini Portrait",
      "artist": "Jan van Eyck",
      "nationality": "Netherlandish",
      "pob": "Maaseik",
      "yob": 1390,
      "yod": 1441,
      "pod": "Bruges",
      "paintingDate": 1434,
      "medium": "Oil on oak panel of 3 vertical boards",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Hey check it out, it is Italian merchant Giovanni di Nicolao Arnolfini and his wife (no name). What a wonderful time for both capatalism and the patriarchy! The artist is flexing with the concave mirror in the background and they also threw in a cute little dog for good measure.",
      "extraLink": "https://en.wikipedia.org/wiki/Arnolfini_Portrait"
    },
    "0507_SexyRobot_HajimeSorayama":{
      "art": "0507_SexyRobot_HajimeSorayama",
      "title": "Robot",
      "artist": "Hajime Sorayama",
      "nationality": "Japanese",
      "pob": "Ehime",
      "yob": 1947,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "BEEP BOOP. HELLO HUMAN. I AM A SEXY ROBOT. LOOK AT MY SEXY RING. BEEP BOOP.",
      "extraLink": ""
    },
    "0601_ArtDeco1930s":{
      "art": "0601_ArtDeco1930s",
      "title": "Art, Goût, Beauté",
      "artist": "Art, Goût, Beauté",
      "nationality": "-",
      "pob": "-",
      "yob": "-",
      "yod": "-",
      "pod": "-",
      "paintingDate": "c.1921-1933",
      "medium": "Stencil",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This drawing is from the French fashion magazine <i>Art, Goût, Beauté</i>. It ran from 1921 to 1933 and its audience were the more upper class, as it gave hints and tips on how to dress, where to go, and how to behave. I'm not sure who drew this piece, or indeed, which issue it appears in, the internet was sorely lacking on this topics.",
      "extraLink": "https://fashionsummedup.com/2021/05/02/art-gout-beaute/"
    },
    "0602_Bathers_RupertBunny":{
      "art": "0602_Bathers_RupertBunny",
      "title": "Bathers",
      "artist": "Rupert Bunny",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1864,
      "yod": 1947,
      "pod": "Melbourne",
      "paintingDate": 1906,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Ah, this is the Edwardian life baby. Nothing like hitting up the old salon and just chilling with the gals, ciggy in hand and clothes optional. Make public baths great again.",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/bathers/"
    },
    "0603_SorrowOfTheKing_HenriMatisse":{
      "art": "0603_SorrowOfTheKing_HenriMatisse",
      "title": "Sorrow of the King",
      "artist": "Henri Matisse",
      "nationality": "French",
      "pob": "Le Cateau-Cambrésis",
      "yob": 1869,
      "yod": 1954,
      "pod": "France",
      "paintingDate": 1952,
      "medium": "Gouache on paper on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Ooooh, I'm the king and I'm sad', is what I imagine the art is saying. This is actually Henri Matisse's last self-portrait. He was in poor health and by the 1950s we had given up painting in favour of creating these collages.",
      "extraLink": "https://www.henrimatisse.org/sorrow-of-the-king.jsp"
    },
    "0604_WilliamAndShirleyFloraAndFauna":{
      "art": "0604_WilliamAndShirleyFloraAndFauna",
      "title": "William and Shirley, flora and fauna 1985",
      "artist": "William Robinson",
      "nationality": "Australian",
      "pob": "Brisbane",
      "yob": 1936,
      "yod": "Present",
      "pod": "",
      "paintingDate": 1985,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at this cute little painting. I got nothing. It's cute!",
      "extraLink": "https://www.artlink.com.au/articles/2555/light-years-william-robinson-and-the-creation-stor/"
    },
    "0701_ForestCunninghamsGap_ConradMartens":{
      "art": "0701_ForestCunninghamsGap_ConradMartens",
      "title": "Forest, Cunningham's Gap",
      "artist": "Conrad Martens",
      "nationality": "English",
      "pob": "London",
      "yob": 1801,
      "yod": 1878,
      "pod": "North Sydney",
      "paintingDate": 1856,
      "medium": "Watercolour on paper",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "British-born Conrad Martens settled in Sydney in 1835 and established a lucrative career. Fifteen years later, however, New South Wales suffered an economic downturn and Martens visited the Moreton Bay area in the hope of obtaining commissions from his connections on the rich pastoral lands of the Darling Downs.\nMartens landed in Brisbane on 17 November 1851, and by 11 December was traversing the steep incline of Cunningham's Gap. This route, the most direct and picturesque from the coast, was also very hazardous. Here Martens, like travellers today, experienced a dramatic contrast between the dense rainforest surrounding Cunningham's Gap and the bright, open Downs.\nThe dark, oppressive scene he records is indicative of the way early settlers regarded the Australian bush. The novelist Marcus Clarke later described the Australian landscape as primitive and frightening, the untamed opposite of the English pastoral ideal.\nThe man on horseback is probably Martens himself on one of his two journeys through the area. The figure functions as a symbol of endeavour, about to break through the obscuring bush into the light of a new life.",
      "extraLink": "https://learning.qagoma.qld.gov.au/artworks/forest-cunninghams-gap/"
    },
    "0702_Untitled1982_JeanMichelBasquiat":{
      "art": "0702_Untitled1982_JeanMichelBasquiat",
      "title": "Untitled (1982)",
      "artist": "Jean-Michel Basquiat",
      "nationality": "American",
      "pob": "New York",
      "yob": 1960,
      "yod": 1988,
      "pod": "New York",
      "paintingDate": 1982,
      "medium": "Acrylic, spray paint and oilstick on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is a skeleton king! Fun fact, Basquiet has numerous artworks he has completed in 1982, most of them titled \"Untitled\" and one of them recently selling for $110 million dollars. So good luck finding anything on this other 1982 untitled piece. Honestly, the artist could have used a better naming convention.",
      "extraLink": "https://news.artnet.com/market/jean-michel-basquiat-most-expensive-works-2016-496796"
    },
    "0703_QueenslandNaive_JamesFardoulus":{
      "art": "0703_QueenslandNaive_JamesFardoulus",
      "title": "The start of Burke and Wills 1860",
      "artist": "James Fardoulys",
      "nationality": "Greek",
      "pob": "Kythera",
      "yob": 1900,
      "yod": 1975,
      "pod": "Brisbane (?)",
      "paintingDate": 1972,
      "medium": "Oil on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Burke and Wills were the first Europeans to cross Australia south to north. They set out in 1860 and finished in 1861. They then died on the return journey. but not all is lost, they expedition uncovered all this grazing land that the Europeans used to further their colonialism.",
      "extraLink": "https://www.qagoma.qld.gov.au/exhibition/james-fardoulys/"
    },
    "0704_GirlWithAPearlEarring_JohannesVermeer":{
      "art": "0704_GirlWithAPearlEarring_JohannesVermeer",
      "title": "Girl with a Pearl Earring",
      "artist": "Johannes Vermeer",
      "nationality": "Dutch",
      "pob": "Delft",
      "yob": 1632,
      "yod": 1675,
      "pod": "Delft",
      "paintingDate": "c.1665",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "She was a girl. Wearing an earring. Can I make it anymore obvious? This is one of the all time classics. I know one of the ai art generators was advertising itself by expanding out the borders of the painting. My personal favourite take on this piece is a Dutch astrophysicist who said, um actually the earring looks to be more polished tin on the grounds of the specular reflection, pear shape, and large size.",
      "extraLink": "https://en.m.wikipedia.org/wiki/Girl_with_a_Pearl_Earring"
    },
    "0705_BirdStealingBaby_SimonGende":{
      "art": "0705_BirdStealingBaby_SimonGende",
      "title": "Bird Stealing Baby",
      "artist": "Simon Gende",
      "nationality": "Paupa New Guinea",
      "pob": "Paupa New Guinean",
      "yob": 1969,
      "yod": "Present",
      "pod": "",
      "paintingDate": 2018,
      "medium": "Acrylic on cotton duck",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This piece is based off a PNG story where there are no men in a village so the bird goes and gets a baby from another place. And the new clan call him Pigeon. All the artists works continue the story (the link below is a wonderful youtube video where he describes it all).",
      "extraLink": "https://youtu.be/o2pjPxaB5cg"
    },
    "0706_WaterLillies_ClaudeMonet":{
      "art": "0706_WaterLillies_ClaudeMonet",
      "title": "Water Lilies",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "1920-1926",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Monet loved nothing more than slinging out the paint and flipping together some water lillies. I mean, if you're good at what you do, but some variety would be nice. He painted a lot of these in the last 30 years of his life when he had catarats which might explain why they're so splodgy.",
      "extraLink": "https://en.wikipedia.org/wiki/Water_Lilies_(Monet_series)"
    },
    "0801_ASundayOnLaGrandeJatte_GeorgesSeurat":{
      "art": "0801_ASundayOnLaGrandeJatte_GeorgesSeurat",
      "title": "A Sunday on La Grande Jatte",
      "artist": "Gorges Seurat",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1859,
      "yod": 1891,
      "pod": "Paris",
      "paintingDate": 1884,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Although you may not think it, this painting is actually massive at 2x3m. I heavily recommend reading the link for the details on this piece because it is fascinating if just from a technical perspective. This artwork was painted with a technique known as Pointillism, basically the entire thing is made up of small uniform dots and our brains mix together the colours that are close to each other.",
      "extraLink": "https://www.artic.edu/artworks/27992/a-sunday-on-la-grande-jatte-1884"
    },
    "0802_TheFightingTemeraire_JosephMallordWilliamTurner":{
      "art": "0802_TheFightingTemeraire_JosephMallordWilliamTurner",
      "title": "The Fighting Temeraire",
      "artist": "Joseph Mallard William Turner",
      "nationality": "English",
      "pob": "Covent Garden",
      "yob": 1775,
      "yod": 1851,
      "pod": "Chelsea",
      "paintingDate": 1838,
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Look at the lights, look at the colours. The full name of this piece is, <i>The Fighting Temeraire, tugged to her last berth to be broken up</i> which is too long to be snappy. It reminds me of the Elven ships sailing east - does it remind you of anything?",
      "extraLink": ""
    },
    "0803_StarryNight_VanGogh":{
      "art": "0803_StarryNight_VanGogh",
      "title": "The Starry Night",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "1889",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "As a part of year 10 English we had to listen to this song called Starry Starry Night and write about our feelings and how it was inspired by this painting. Coincidentally, this was also around the time that I grew dissallusioned in English as a subject.",
      "extraLink": "https://www.youtube.com/watch?v=dipFMJckZOM"
    },
    "0804_Nighthawks_EdwardHopper":{
      "art": "0804_Nighthawks_EdwardHopper",
      "title": "Nighthawks",
      "artist": "Edward Hopper",
      "nationality": "American",
      "pob": "Nyack",
      "yob": 1882,
      "yod": 1967,
      "pod": "Washington Square North",
      "paintingDate": "1942",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Eeh see? We're just a couple of nighthawks hanging out at our favourite diner in Chicago see? I'll have a large apple pie and milkshake see? My favpurite bit of trivia about this painting is Hopper's wife kept notes on all of Hopper's works. In it she says the intended name for the piece was originally <iz.Night Hawks</i>. Is te actual name better? You decide. Perform a half flush for <i>Nighthawks</i> and a full flush for <i>Night Hawks</i>",
      "extraLink": "https://www.artic.edu/artworks/111628/nighthawks"
    },
    "0805a_PaulGuilaume_AmedeoModigliani":{
      "art": "0805a_PaulGuilaume_AmedeoModigliani",
      "title": "Paul Guillaume",
      "artist": "Amedeo Modigliani",
      "nationality": "Italian",
      "pob": "Livorno",
      "yob": 1884,
      "yod": 1920,
      "pod": "Saint-Étienne",
      "paintingDate": "c.1915",
      "medium": "Oil on cardboard probably",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "What an absolute trek it was to hunt this one down and in the end I didn't really acheive it fully. This piece is a portrait of Paul Guillaume by Modigliani but honrstly, Modigliani churned these out for some reason. If you can find any more info that would be very helpful.",
      "extraLink": "https://www.ngv.vic.gov.au/orangerie/modiglianiimage.html"
    },
    "0901_Heritage_CaiGuo-Qiang":{
      "art": "0901_Heritage_CaiGuo-Qiang",
      "title": "Heritage",
      "artist": "Cai Guo-Qiang",
      "nationality": "Chinese",
      "pob": "Quanzhou",
      "yob": 1957,
      "yod": "Present",
      "pod": "",
      "paintingDate": "2013",
      "medium": "Animals: polystyrene, gauze, resin and hide. Installed with artificial watering hole: water, sand, drip mechanism",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "I know the image here doesn't match to the postcard in the physical Toilet Gallery. This image was taken from a different angle because it's a massive installation piece and not a painting. A single drop of water drums into the centre of the lake.",
      "extraLink": "https://blog.qagoma.qld.gov.au/cai-guo-qiang-heritage-99-replicas-of-animals/"
    },
    "0902_SpiritOfThePlains_SydneyLong":{
      "art": "0902_SpiritOfThePlains_SydneyLong",
      "title": "Spirit of the Plains",
      "artist": "Sydney Long",
      "nationality": "Australian",
      "pob": "Goulburn",
      "yob": 1871,
      "yod": 1955,
      "pod": "London",
      "paintingDate": "1897",
      "medium": "Oil on canvas on wood",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Naked lady leads weird Australian birds across the landscape.",
      "extraLink": "https://blog.qagoma.qld.gov.au/dancing-across-the-landscape-is-the-spirit-of-the-plains-sydney-long-australia/"
    },
    "0903_BonnieSue1964_MargaretOlley":{
      "art": "0903_BonnieSue1964_MargaretOlley",
      "title": "Bonnie Sue 1964",
      "artist": "Margaret Olley",
      "nationality": "Australian",
      "pob": "Lismore",
      "yob": 1923,
      "yod": 2011,
      "pod": "Paddington",
      "paintingDate": "1964",
      "medium": "Oil on board",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Jonah says that this one looks like Tabouli, and he's not far off. The painter loved her dog (Bonnie Sue) so much that she did a few paintings of them. I think we can all agree it is very aDOGable (instead of adorable).",
      "extraLink": "https://blog.qagoma.qld.gov.au/meet-bonnie-sue-margaret-olleys-beloved-pug/"
    },
    "0904_NudeWomenReading_RobertDelaunay":{
      "art": "0904_NudeWomenReading_RobertDelaunay",
      "title": "Nude Woman Reading",
      "artist": "Robert Delaunay",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1885,
      "yod": 1941,
      "pod": "Montpellier",
      "paintingDate": "1915",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "Here we see a nude woman reading.",
      "extraLink": "https://artsandculture.google.com/asset/nude-woman-reading-robert-delaunay/-QFbKBNtET-twQ?hl=en"
    },
    "0905_LasMeninas_DiegoVelázquez":{
      "art": "0905_LasMeninas_DiegoVelázquez",
      "title": "",
      "artist": "Diego Velázquez",
      "nationality": "Spanish",
      "pob": "Seville",
      "yob": 1599,
      "yod": 1660,
      "pod": "Madrid",
      "paintingDate": "1656",
      "medium": "Oil on canvas",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": "https://www.britannica.com/topic/Las-meninas"
    },
    "1001_PreparingToGoOut_TaniguchiFumie":{
      "art": "1001_PreparingToGoOut_TaniguchiFumie",
      "title": "",
      "artist": "Fumie Taniguchi",
      "nationality": "Japanese",
      "pob": "Tokyo",
      "yob": 1910,
      "yod": 2001,
      "pod": "Los Angeles",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": "https://www.ngv.vic.gov.au/essay/rediscovering-fumie-taniguchi/"
    },
    "1002_Self-portraitWithModel_ErnestLudwigKirchner":{
      "art": "1002_Self-portraitWithModel_ErnestLudwigKirchner",
      "title": "",
      "artist": "Ernest Ludwig Kirchner",
      "nationality": "German",
      "pob": "Aschaffenburg",
      "yob": 1880,
      "yod": 1938,
      "pod": "Frauenkirch",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1003_YellowRedBlue_WassilyKandinsky":{
      "art": "1003_YellowRedBlue_WassilyKandinsky",
      "title": "",
      "artist": "Wassily Kandinsky",
      "nationality": "Russian",
      "pob": "Moscow",
      "yob": 1866,
      "yod": 1944,
      "pod": "Neuilly-sur-Seine",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1004_PortraitOfDoraMara_PabloPicasso":{
      "art": "1004_PortraitOfDoraMara_PabloPicasso",
      "title": "",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1005_BoulevardMontmartre_CamillePissarro":{
      "art": "1005_BoulevardMontmartre_CamillePissarro",
      "title": "",
      "artist": "Camille Pissarro",
      "nationality": "Danish-French",
      "pob": "Charlotte Amalie",
      "yob": 1830,
      "yod": 1903,
      "pod": "Paris",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1101_ActualFractual_HowardArkley":{
      "art": "1101_ActualFractual_HowardArkley",
      "title": "",
      "artist": "Howard Arkley",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1951,
      "yod": 1999,
      "pod": "Mebourne",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1102_TheHuntersInTheSnow_PeterBruegel":{
      "art": "1102_TheHuntersInTheSnow_PeterBruegel",
      "title": "",
      "artist": "Pieter Bruegel the Elder",
      "nationality": "Dutch",
      "pob": "Breda or Breugel",
      "yob": "c. 1525-1530",
      "yod": 1569,
      "pod": "Brussels",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1103_TigerInATropicalStorm_HenriRousseau":{
      "art": "1103_TigerInATropicalStorm_HenriRousseau",
      "title": "",
      "artist": "Henri Rousseau",
      "nationality": "French",
      "pob": "Laval",
      "yob": 1844,
      "yod": 1910,
      "pod": "Paris",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1104_HaystackInTheMorning_ClaudeMonet":{
      "art": "1104_HaystackInTheMorning_ClaudeMonet",
      "title": "",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1105_BruteFolly_FranciscoGoyaYLucientes":{
      "art": "1105_BruteFolly_FranciscoGoyaYLucientes",
      "title": "",
      "artist": "Francisco Goya",
      "nationality": "Spanish",
      "pob": "Fuendetodos",
      "yob": 1746,
      "yod": 1828,
      "pod": "Bordeaux",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1201_WaxDogsOnLakeEyre_LinOnus":{
      "art": "1201_WaxDogsOnLakeEyre_LinOnus",
      "title": "",
      "artist": "Lin Onus",
      "nationality": "Australian",
      "pob": "Boroondara",
      "yob": 1948,
      "yod": 1996,
      "pod": "Naarm",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": "https://www.artgallery.nsw.gov.au/collection/artists/onus-lin/"
    },
    "1202_Summertime_MaryCassatt":{
      "art": "1202_Summertime_MaryCassatt",
      "title": "",
      "artist": "Mary Cassat",
      "nationality": "American",
      "pob": "Allegheny",
      "yob": 1844,
      "yod": 1926,
      "pod": "Château de Beaufresne",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1203_BalDuMoulinDeLaGalette_Pierre-AugusteRenoir":{
      "art": "1203_BalDuMoulinDeLaGalette_Pierre-AugusteRenoir",
      "title": "",
      "artist": "Pierre-Auguste Renoir",
      "nationality": "French",
      "pob": "Limoges",
      "yob": 1841,
      "yod": 1919,
      "pod": "Cagnes-sur-Mer",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1301_UntitledDog_KeithHarring":{
      "art": "1301_UntitledDog_KeithHarring",
      "title": "",
      "artist": "Keith Harring",
      "nationality": "American",
      "pob": "Reading",
      "yob": 1958,
      "yod": 1990,
      "pod": "New York",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1302_IdeasOfBarak_VernonAhKee":{
      "art": "1302_IdeasOfBarak_VernonAhKee",
      "title": "",
      "artist": "Vernon Ah Kee",
      "nationality": "Australian",
      "pob": "Innisfail",
      "yob": 1967,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": "https://www.ngv.vic.gov.au/multimedia/vernon-ah-kee-investigating-ideas-of-barak/"
    },
    "1303_Number6_JacksonPollock":{
      "art": "1303_Number6_JacksonPollock",
      "title": "",
      "artist": "Jackson Pollock",
      "nationality": "American",
      "pob": "Cody",
      "yob": 1912,
      "yod": 1956,
      "pod": "Springs",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1304_WhenWillYouMarry_PaulGauguin":{
      "art": "1304_WhenWillYouMarry_PaulGauguin",
      "title": "",
      "artist": "Paul Gaugin",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1848,
      "yod": 1903,
      "pod": "Atuona",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1305_TeaAndCoffeeSalon_SabōSaekiShunko":{
      "art": "1305_TeaAndCoffeeSalon_SabōSaekiShunko",
      "title": "Tea and coffee salon, Sabō",
      "artist": "Saeki Shunko",
      "nationality": "Japanese",
      "pob": "Toyama Prefecture",
      "yob": 1909,
      "yod": 1942,
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1306_TheSonOfMan_ReneMagritte":{
      "art": "1306_TheSonOfMan_ReneMagritte",
      "title": "",
      "artist": "Rene Magritte",
      "nationality": "Belgian",
      "pob": "Lessines",
      "yob": 1898,
      "yod": 1967,
      "pod": "Rue des Mimosas",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1307_IAmAMermaid_EuniceDjerrkŋuYunupiŋu":{
      "art": "1307_IAmAMermaid_EuniceDjerrkŋuYunupiŋu",
      "title": "I am a Mermaid",
      "artist": "Djerrkŋu Yunupiŋu (Eunice)",
      "nationality": "Australian",
      "pob": "Inglis Island",
      "yob": "c.1945",
      "yod": 2022,
      "pod": "Yirrkala",
      "paintingDate": 2020,
      "medium": "Earth pigments and recycled print toner on Stringybark (Eucalyptus sp.)",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "This is my favourite one",
      "extraLink": "https://www.ngv.vic.gov.au/multimedia/djerrkngu-yunupingu-i-am-a-mermaid/"
    },
    "1401_ElephantWalking_EadweardMuybridge":{
      "art": "1401_ElephantWalking_EadweardMuybridge",
      "title": "",
      "artist": "Eadweard Muybridge",
      "nationality": "English",
      "pob": "Kingston upon Thames",
      "yob": 1830,
      "yod": 1904,
      "pod": "Kingston upon Thames",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1402_MonaLisa_LeonardoDaVinci":{
      "art": "1402_MonaLisa_LeonardoDaVinci",
      "title": "",
      "artist": "Leonardo da Vinci",
      "nationality": "Italian",
      "pob": "Anchiano",
      "yob": 1452,
      "yod": 1519,
      "pod": "Château du Clos Lucé",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1403_HousesAtAuvers_VincentVanGogh":{
      "art": "1403_HousesAtAuvers_VincentVanGogh",
      "title": "",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1404_TheBanquetOfCleopatra_GiovanniBattistaTiepolo":{
      "art": "1404_TheBanquetOfCleopatra_GiovanniBattistaTiepolo",
      "title": "",
      "artist": "Giovanni Battista Tiepolo",
      "nationality": "Italian",
      "pob": "Venice",
      "yob": 1696,
      "yod": 1770,
      "pod": "Madrid",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1405_HorsesBathingInTheSea_LucyKemp":{
      "art": "1405_HorsesBathingInTheSea_LucyKemp",
      "title": "",
      "artist": "Lucy Kemp-Welch",
      "nationality": "British",
      "pob": "Bournemouth",
      "yob": 1869,
      "yod": 1958,
      "pod": "Watford",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1501_ThePersistanceOfMemory_SalvadorDali":{
      "art": "1501_ThePersistanceOfMemory_SalvadorDali",
      "title": "",
      "artist": "Salvador Dali",
      "nationality": "Spanish",
      "pob": "Figueres",
      "yob": 1904,
      "yod": 1989,
      "pod": "Figueres",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1502_DancersInBlue_EdgarDagas":{
      "art": "1502_DancersInBlue_EdgarDagas",
      "title": "",
      "artist": "Edgar Degas",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1834,
      "yod": 1917,
      "pod": "Paris",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1503_MorningSunlightOnTheSnow_CamillePissarro":{
      "art": "1503_MorningSunlightOnTheSnow_CamillePissarro",
      "title": "",
      "artist": "Camille Pissarro",
      "nationality": "Danish-French",
      "pob": "Charlotte Amalie",
      "yob": 1830,
      "yod": 1903,
      "pod": "Paris",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1504_FlyingCloud_KennethMacqueen":{
      "art": "1504_FlyingCloud_KennethMacqueen",
      "title": "",
      "artist": "Kenneth McQueen",
      "nationality": "Australian",
      "pob": "",
      "yob": 1897,
      "yod": 1960,
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1505_TheWaterLilyPond_ClaudeMonet":{
      "art": "1505_TheWaterLilyPond_ClaudeMonet",
      "title": "",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1506_It'sOurDestiny2_EkoNugroho":{
      "art": "1506_It'sOurDestiny2_EkoNugroho",
      "title": "",
      "artist": "Eko Nugroho",
      "nationality": "Indonesian",
      "pob": "Yogyakarta",
      "yob": 1977,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1507_AbstractPainting_GerhardRichter":{
      "art": "1507_AbstractPainting_GerhardRichter",
      "title": "",
      "artist": "Gerhard Richter",
      "nationality": "German",
      "pob": "Dresden",
      "yob": 1932,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1601_HamLongStreet_BuiXuanPhai":{
      "art": "1601_HamLongStreet_BuiXuanPhai",
      "title": "",
      "artist": "Bùi Xuân Phái",
      "nationality": "Vietnamese",
      "pob": "Hanoi",
      "yob": 1920,
      "yod": 1988,
      "pod": "Hanoi",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1602_Self-Portrait_VincentVanGogh":{
      "art": "1602_Self-Portrait_VincentVanGogh",
      "title": "",
      "artist": "Vincent van Gogh",
      "nationality": "Dutch",
      "pob": "Zundert",
      "yob": 1853,
      "yod": 1890,
      "pod": "Auvers-sur-Oise",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1603_DrySalvages_JohnOlsen":{
      "art": "1603_DrySalvages_JohnOlsen",
      "title": "",
      "artist": "John Olsen",
      "nationality": "Australian",
      "pob": "Newcastle",
      "yob": 1928,
      "yod": 2023,
      "pod": "Bowrai",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1604_TheLacquerRoom_GraceCossingtonSmith":{
      "art": "1604_TheLacquerRoom_GraceCossingtonSmith",
      "title": "",
      "artist": "Grace Cossington Smith",
      "nationality": "Australian",
      "pob": "Neutral Bay",
      "yob": 1892,
      "yod": 1984,
      "pod": "Roseville",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1605_JetStream_JulianOpie":{
      "art": "1605_JetStream_JulianOpie",
      "title": "",
      "artist": "Julian Opie",
      "nationality": "British",
      "pob": "London",
      "yob": 1958,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1606_MeadowWithPoplars_ClaudeMonet":{
      "art": "1606_MeadowWithPoplars_ClaudeMonet",
      "title": "",
      "artist": "Claude Monet",
      "nationality": "French",
      "pob": "Paris",
      "yob": 1840,
      "yod": 1926,
      "pod": "Giverny",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1701_MondayMorning_VidaLahey":{
      "art": "1701_MondayMorning_VidaLahey",
      "title": "",
      "artist": "Vida Lahey",
      "nationality": "Australian",
      "pob": "Pimpama",
      "yob": 1882,
      "yod": 1968,
      "pod": "Wonga",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1702_WomanInAnArmchair_PabloPicasso":{
      "art": "1702_WomanInAnArmchair_PabloPicasso",
      "title": "",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1703_ASceneOnTheIceNearATown_HendrickAvercamp":{
      "art": "1703_ASceneOnTheIceNearATown_HendrickAvercamp",
      "title": "",
      "artist": "Hendrick Avercamp",
      "nationality": "Dutch",
      "pob": "Amsterdam",
      "yob": 1585,
      "yod": 1634,
      "pod": "Kampen",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1704_ApplesAndOranges_PaulCézanne":{
      "art": "1704_ApplesAndOranges_PaulCézanne",
      "title": "",
      "artist": "Paul Cézanne",
      "nationality": "French",
      "pob": "Aix-en-Provence",
      "yob": 1839,
      "yod": 1906,
      "pod": "Aix-en-Provence",
      "paintingDate": 1900,
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1801_AgainstAllOdds_BrookAndrew":{
      "art": "1801_AgainstAllOdds_BrookAndrew",
      "title": "",
      "artist": "Brook Andrew",
      "nationality": "Australian",
      "pob": "Sydney",
      "yob": 1970,
      "yod": "Present",
      "pod": "",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1802_HorsemanInLandscape_FredWilliams":{
      "art": "1802_HorsemanInLandscape_FredWilliams",
      "title": "",
      "artist": "Fred Williams",
      "nationality": "Australian",
      "pob": "Richmond",
      "yob": 1927,
      "yod": 1982,
      "pod": "Hawthorn",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1803_MortaruruWithRedOverhead_AleksandrVolkov":{
      "art": "1803_MortaruruWithRedOverhead_AleksandrVolkov",
      "title": "",
      "artist": "Alexander Nikolaevich Volkov",
      "nationality": "Russian",
      "pob": "Fergana",
      "yob": 1886,
      "yod": 1957,
      "pod": "Tashkent",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1804_ALionAttackingAHorse_GeorgeStubbs":{
      "art": "1804_ALionAttackingAHorse_GeorgeStubbs",
      "title": "",
      "artist": "George Stubbs",
      "nationality": "English",
      "pob": "Liverpool",
      "yob": 1724,
      "yod": 1806,
      "pod": "Marylebone",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1805_ManInBlue_PabloPicasso":{
      "art": "1805_ManInBlue_PabloPicasso",
      "title": "",
      "artist": "Pablo Picasso",
      "nationality": "Spanish",
      "pob": "Málaga",
      "yob": 1881,
      "yod": 1973,
      "pod": "Mougins",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    },
    "1806_SpringScene_RupertBunny":{
      "art": "1806_SpringScene_RupertBunny",
      "title": "",
      "artist": "Rupert Bunny",
      "nationality": "Australian",
      "pob": "Melbourne",
      "yob": 1864,
      "yod": 1947,
      "pod": "Melbourne",
      "paintingDate": "",
      "medium": "",
      "style": "",
      "genre": "",
      "period": "",
      "comment": "",
      "extraLink": ""
    }
  }